;;;; -*- Mode: Lisp; Syntax: ANSI-Common-Lisp; Base: 10 -*-
;;;;
;;;; tree/types.lisp
;;;;
;;;; SwarmTree ADT Core Types - Base classes and protocols for hierarchical orchestration.
;;;;
;;;; This module defines the core algebraic data type for the SwarmTree:
;;;;
;;;;   SwarmTree = Leaf(SwarmInstance) | Node(Orchestrator, [SwarmTree])
;;;;
;;;; The tree structure enables:
;;;;   - Arbitrary nesting depth (practical systems use 2-4 levels)
;;;;   - Independent sw4rm instances as composable units
;;;;   - Hierarchical routing with path-based message delivery
;;;;   - Failure isolation at sw4rm boundaries
;;;;
;;;; Architecture:
;;;;   - SWARM-TREE: Base class for all tree nodes
;;;;   - SWARM-LEAF: Leaf node wrapping a Python sw4rm instance (via gRPC)
;;;;   - SWARM-NODE: Inner orchestrator node coordinating children
;;;;
;;;; Generic function protocols define the tree operations:
;;;;   - ROUTE-ENVELOPE: Route envelope through this node
;;;;   - RECEIVE-ENVELOPE: Receive envelope at this node
;;;;   - REGISTER-CHILD: Register a child node
;;;;   - UNREGISTER-CHILD: Remove child by ID
;;;;   - GET-CHILD: Retrieve child by ID
;;;;   - LIST-CHILDREN: List all children
;;;;   - NODE-DEPTH: Compute depth in tree
;;;;
;;;; Version: 0.6.0
;;;; Author: SW4RM Platform Team
;;;; License: Apache 2.0

(in-package :sw4rm-orchestrator.tree)

;;;; ============================================================================
;;;; Simple Metrics Collector (placeholder until metrics module is implemented)
;;;; ============================================================================

(defstruct metrics-collector
  "Simple metrics collector for tracking node statistics.

  This is a placeholder implementation. A full metrics system will be
  implemented in sw4rm-orchestrator.metrics package.

  Slots:
    counters - Hash table of counter metrics (name -> value)
    gauges - Hash table of gauge metrics (name -> value)
    histograms - Hash table of histogram metrics (name -> list of values)"
  (counters (make-hash-table :test 'equal) :type hash-table)
  (gauges (make-hash-table :test 'equal) :type hash-table)
  (histograms (make-hash-table :test 'equal) :type hash-table))

;; Note: make-metrics-collector is automatically generated by defstruct above.
;; No need to define it manually.

(defun record-metric (collector metric-name value &key (type :gauge))
  "Record a metric value.

  Args:
    collector - The METRICS-COLLECTOR instance
    metric-name - Keyword or string identifying the metric
    value - Numeric value to record
    type - Type of metric (:gauge, :counter, or :histogram)

  Returns:
    The recorded value.

  Examples:
    (record-metric collector :route-latency 42 :type :histogram)
    (record-metric collector :messages-routed 1 :type :counter)"
  (declare (type metrics-collector collector)
           (type (or keyword string) metric-name)
           (type number value)
           (type (member :gauge :counter :histogram) type))
  (let ((key (if (keywordp metric-name)
                 (string-downcase (symbol-name metric-name))
                 metric-name)))
    (ecase type
      (:gauge
       (setf (gethash key (metrics-collector-gauges collector)) value))
      (:counter
       (incf (gethash key (metrics-collector-counters collector) 0) value))
      (:histogram
       (push value (gethash key (metrics-collector-histograms collector) nil))))
    value))

;;;; ============================================================================
;;;; Node Status Enum
;;;; ============================================================================

(deftype node-status ()
  "Status of a swarm tree node.

  Values:
    :INITIALIZING - Node is being set up, not ready for traffic
    :READY - Node is healthy and ready to route messages
    :DEGRADED - Node is experiencing issues but still operational (legacy/generic)
    :UNREACHABLE - Node or leaf cannot be contacted (network/connectivity failure)
    :PARTIAL - Some child leaves are healthy, others degraded (mixed health)
    :RECOVERING - WAL replay or checkpoint restore in progress
    :SHUTTING-DOWN - Node is gracefully shutting down

  Note:
    The :DEGRADED state is retained for backward compatibility but is now more
    specific with :UNREACHABLE, :PARTIAL, and :RECOVERING states for better
    observability and operational clarity.

  Status transitions:
    :INITIALIZING -> :READY (after successful setup)
    :INITIALIZING -> :RECOVERING (during checkpoint/WAL restore)
    :RECOVERING -> :READY (after successful recovery)
    :RECOVERING -> :DEGRADED (on partial recovery failure)
    :READY -> :DEGRADED (on non-fatal errors)
    :READY -> :UNREACHABLE (on connectivity loss)
    :READY -> :PARTIAL (when some children become unhealthy)
    :PARTIAL -> :READY (when all children recover)
    :PARTIAL -> :DEGRADED (when health deteriorates further)
    :UNREACHABLE -> :RECOVERING (attempting to reconnect)
    :UNREACHABLE -> :READY (on successful reconnection)
    Any -> :SHUTTING-DOWN (on shutdown request)

  See Also:
    SWARM-TREE class, GET-HEALTH-STATUS"
  '(member :initializing :ready :degraded :unreachable :partial :recovering :shutting-down))

;;;; ============================================================================
;;;; Base Class: SWARM-TREE
;;;; ============================================================================

(defclass swarm-tree ()
  ((id
    :initarg :id
    :reader swarm-id
    :type string
    :documentation "Unique identifier for this swarm tree node.

    This ID must be unique across all nodes in the tree. It is used for
    routing, logging, and identification. Once set at initialization, it
    cannot be changed (read-only).")

   (parent
    :initarg :parent
    :accessor parent-node
    :initform nil
    :type (or null swarm-tree)
    :documentation "Parent node in the tree, or NIL if this is the root.

    The parent reference enables upward routing when the target swarm is
    not found in this subtree. Circular references are not validated at
    construction time but will cause routing loops (detected by hop limits).")

   (metrics
    :accessor node-metrics
    :initform (make-metrics-collector)
    :type metrics-collector
    :documentation "Metrics collector for tracking node operations.

    Automatically initialized on node creation. Use RECORD-METRIC to track
    routing latency, message counts, and other operational metrics.")

   (created-at
    :reader node-created-at
    :initform (get-universal-time)
    :type integer
    :documentation "Universal time when this node was created.

    Timestamp in Common Lisp universal time format (seconds since 1900-01-01).
    Used for diagnostics, logging, and uptime calculations.")

   (status
    :accessor node-status
    :initform :initializing
    :type node-status
    :documentation "Current operational status of this node.

    Valid values: :INITIALIZING, :READY, :DEGRADED, :SHUTTING-DOWN

    Status transitions:
      :INITIALIZING -> :READY (after successful setup)
      :READY -> :DEGRADED (on non-fatal errors)
      :DEGRADED -> :READY (after recovery)
      Any -> :SHUTTING-DOWN (on shutdown request)"))

  (:documentation "Base class for all swarm tree nodes.

  This is the root of the class hierarchy for the SwarmTree ADT. All tree
  nodes (both leaves and inner nodes) inherit from this class.

  The SWARM-TREE defines common properties and operations for all nodes:
    - Unique identification (ID)
    - Tree structure (parent reference)
    - Operational metrics (counters, gauges, histograms)
    - Lifecycle tracking (creation time, status)

  Subclasses:
    - SWARM-LEAF: Wraps a Python sw4rm instance accessible via gRPC
    - SWARM-NODE: Orchestrator node coordinating multiple children

  Protocol methods (implemented by subclasses):
    - ROUTE-ENVELOPE: Route cross-swarm messages
    - RECEIVE-ENVELOPE: Handle messages destined for this node
    - REGISTER-CHILD: Add child nodes (SWARM-NODE only)
    - UNREGISTER-CHILD: Remove child nodes (SWARM-NODE only)
    - GET-CHILD: Retrieve child by ID (SWARM-NODE only)
    - LIST-CHILDREN: List all children (SWARM-NODE only)
    - NODE-DEPTH: Calculate depth in tree

  See Also:
    SWARM-LEAF, SWARM-NODE, ROUTE-ENVELOPE, REGISTER-CHILD"))

(defmethod initialize-instance :after ((node swarm-tree) &key)
  "Validate and initialize a swarm-tree instance.

  Ensures:
    - ID is provided and is a non-empty string
    - Parent (if provided) is a SWARM-TREE instance
    - Status is a valid NODE-STATUS

  Raises:
    ERROR if validation fails."
  (unless (slot-boundp node 'id)
    (error "SWARM-TREE requires an :id argument"))
  (unless (and (stringp (swarm-id node))
               (> (length (swarm-id node)) 0))
    (error "SWARM-TREE :id must be a non-empty string, got: ~S" (swarm-id node)))
  (when (parent-node node)
    (unless (typep (parent-node node) 'swarm-tree)
      (error "SWARM-TREE :parent must be a SWARM-TREE instance, got: ~S"
             (type-of (parent-node node))))))

;;;; ============================================================================
;;;; SWARM-LEAF Class: Wraps Python sw4rm instance
;;;; ============================================================================

(defclass swarm-leaf (swarm-tree)
  ((scheduler
    :initarg :scheduler
    :accessor leaf-scheduler
    :initform nil
    :type t
    :documentation "Reference to Python scheduler (accessed via gRPC stub).

    This is typically a gRPC client stub or reference that allows calling
    scheduler methods on the remote Python sw4rm instance. The actual type
    depends on the gRPC implementation.")

   (router
    :initarg :router
    :accessor leaf-router
    :initform nil
    :type t
    :documentation "Reference to Python router (accessed via gRPC stub).

    This is typically a gRPC client stub or reference that allows calling
    router methods on the remote Python sw4rm instance.")

   (registry
    :initarg :registry
    :accessor leaf-registry
    :initform nil
    :type t
    :documentation "Reference to Python registry (accessed via gRPC stub).

    This is typically a gRPC client stub or reference that allows calling
    registry methods on the remote Python sw4rm instance.")

   (agents
    :initarg :agents
    :accessor leaf-agents
    :initform nil
    :type list
    :documentation "List of agent identifiers registered in this leaf.

    Each entry is typically a string agent ID. This list is populated when
    agents register with the leaf swarm and is used for routing decisions
    and discovery.")

   (grpc-channel
    :initarg :grpc-channel
    :accessor grpc-channel
    :initform nil
    :type t
    :documentation "Active gRPC channel to the Python sw4rm instance.

    This is the underlying network connection used by the gRPC client stubs.
    The channel must be explicitly opened and closed. Type depends on the
    gRPC library implementation.")

   (grpc-client
    :initarg :grpc-client
    :accessor leaf-grpc-client
    :initform nil
    :type t
    :documentation "High-level gRPC client wrapper for this leaf.

    This is typically an instance of LEAF-GRPC-CLIENT (from the grpc package)
    that provides connection management, envelope delivery, and heartbeat
    monitoring.")

   (host
    :initarg :host
    :reader leaf-host
    :initform "localhost"
    :type string
    :documentation "Hostname or IP address of the Python sw4rm instance.

    Used to establish the gRPC connection. Default is 'localhost' for
    local development.")

   (port
    :initarg :port
    :reader leaf-port
    :initform 50051
    :type (integer 1 65535)
    :documentation "Port number of the Python sw4rm gRPC service.

    Must be between 1 and 65535. Default is 50051 (common gRPC port).")

   (last-heartbeat
    :accessor leaf-last-heartbeat
    :initform nil
    :type (or null integer)
    :documentation "Universal time of last successful heartbeat from this leaf.

    NIL if no heartbeat has been received yet. Used to detect stale or
    disconnected leaves. Updated automatically by the heartbeat stream
    handler.")

   (capabilities
    :initarg :capabilities
    :accessor leaf-capabilities
    :initform nil
    :type list
    :documentation "List of capability keywords advertised by this leaf.

    Capabilities might include:
      :nlp - Natural language processing
      :vision - Computer vision
      :tool-use - Function calling
      :streaming - Supports streaming responses

    Used for capability-based routing and service discovery."))

  (:documentation "Leaf node representing a complete Python sw4rm instance.

  A SWARM-LEAF wraps a Python sw4rm instance running in a separate process
  (typically in a separate container). The orchestrator communicates with
  the leaf via gRPC to:
    - Deliver cross-swarm envelopes
    - Monitor health via heartbeats
    - Query agent registry
    - Retrieve metrics

  Connection lifecycle:
    1. Create SWARM-LEAF with :host and :port
    2. Create LEAF-GRPC-CLIENT (from grpc package)
    3. CONNECT establishes gRPC channel
    4. DELIVER-ENVELOPE sends messages to leaf
    5. HEARTBEAT-STREAM monitors health
    6. DISCONNECT closes gRPC channel on shutdown

  Routing behavior:
    - If target swarm matches this leaf's ID, deliver locally
    - Otherwise, route to parent (upward routing)

  Slots:
    scheduler - Python scheduler stub
    router - Python router stub
    registry - Python registry stub
    agents - List of agent IDs in this leaf
    grpc-channel - Underlying gRPC channel
    grpc-client - High-level client wrapper
    host - Hostname/IP of Python instance
    port - gRPC service port
    last-heartbeat - Last heartbeat timestamp
    capabilities - Advertised capabilities

  See Also:
    SWARM-TREE, SWARM-NODE, LEAF-GRPC-CLIENT, CONNECT, DELIVER-ENVELOPE"))

(defmethod initialize-instance :after ((leaf swarm-leaf) &key)
  "Validate swarm-leaf instance.

  Ensures:
    - Port is in valid range (1-65535)
    - Host is a non-empty string

  Raises:
    ERROR if validation fails."
  (unless (and (integerp (leaf-port leaf))
               (<= 1 (leaf-port leaf) 65535))
    (error "SWARM-LEAF :port must be between 1 and 65535, got: ~S" (leaf-port leaf)))
  (unless (and (stringp (leaf-host leaf))
               (> (length (leaf-host leaf)) 0))
    (error "SWARM-LEAF :host must be a non-empty string, got: ~S" (leaf-host leaf))))

;;;; ============================================================================
;;;; SWARM-NODE Class: Inner orchestrator node
;;;; ============================================================================

(defclass swarm-node (swarm-tree)
  ((children
    :accessor node-children
    :initform (make-hash-table :test 'equal)
    :type hash-table
    :documentation "Hash table mapping child IDs (strings) to SWARM-TREE instances.

    This is the core data structure for the tree hierarchy. Children can be
    either SWARM-LEAF instances (wrapping Python sw4rms) or other SWARM-NODE
    instances (enabling multi-level trees).

    Use REGISTER-CHILD and UNREGISTER-CHILD to modify, GET-CHILD to retrieve,
    and LIST-CHILDREN to enumerate.")

   (routing-table
    :accessor routing-table
    :initform nil
    :type t
    :documentation "Routing table for efficient cross-swarm message delivery.

    Maps target swarm IDs to next-hop child IDs. This is populated by:
      - Direct child registration (REGISTER-CHILD)
      - Gossip protocol (children advertise their subtrees)
      - Topology discovery

    The routing table structure is defined in the sw4rm-orchestrator.routing
    package. Use MAKE-ROUTING-TABLE to initialize, LOOKUP-ROUTE to query,
    and ADD-ROUTE/REMOVE-ROUTE to modify.")

   (policy
    :initarg :policy
    :accessor node-policy
    :initform nil
    :type t
    :documentation "Orchestration policy for this node.

    Defines routing strategies, load balancing, failure handling, and other
    coordination behaviors. The policy structure is defined in the coordination
    package.

    If NIL, uses *DEFAULT-ORCHESTRATION-POLICY*. Custom policies can be
    provided via :policy initarg."))

  (:documentation "Inner orchestrator node coordinating child sw4rms.

  A SWARM-NODE is an orchestrator that manages multiple child nodes (either
  leaves or other orchestrators) and routes cross-swarm messages between them.

  Key responsibilities:
    - Register and unregister child nodes
    - Route envelopes to appropriate children
    - Maintain routing table for efficient delivery
    - Apply orchestration policies (load balancing, failover, etc.)
    - Aggregate metrics from children

  Routing algorithm:
    1. If target swarm is this node, receive locally (rare, meta-operations)
    2. If target swarm is a direct child, route to child
    3. If routing table knows the path, route via next hop
    4. If parent exists, route upward
    5. For broadcast targets, route to all children
    6. Otherwise, reject (target not found)

  Tree operations:
    - REGISTER-CHILD: Add a child node, update routing table
    - UNREGISTER-CHILD: Remove a child node, clean up routes
    - GET-CHILD: Retrieve child by ID
    - LIST-CHILDREN: Enumerate all children

  Slots:
    children - Hash table (child-id -> swarm-tree)
    routing-table - Routing table for message delivery
    policy - Orchestration policy

  See Also:
    SWARM-TREE, SWARM-LEAF, REGISTER-CHILD, ROUTE-ENVELOPE, ROUTING-TABLE"))

;;;; ============================================================================
;;;; Generic Function Protocols
;;;; ============================================================================

(defgeneric route-envelope (node envelope)
  (:documentation "Route envelope through this node.

  This is the core routing operation for cross-swarm message delivery. Each
  node type implements its own routing logic:

  SWARM-NODE routing:
    1. Check if target is this node (local delivery)
    2. Check if target is direct child (route to child)
    3. Consult routing table for indirect routes
    4. Route to parent if available (upward routing)
    5. Broadcast to all children if target is :BROADCAST
    6. Reject if no route found

  SWARM-LEAF routing:
    1. Check if target is this leaf (deliver via gRPC)
    2. Route to parent (leaves cannot route to siblings)
    3. Reject if no parent (orphan leaf)

  The envelope is modified in-place:
    - Hop count is incremented
    - Node ID is added to path
    - Deadline is checked

  Args:
    node - SWARM-TREE instance (node or leaf)
    envelope - CROSS-SWARM-ENVELOPE to route

  Returns:
    ROUTING-RESULT with decision, target, and reason.

  Raises:
    MAX-HOPS-EXCEEDED if hop limit reached
    ENVELOPE-EXPIRED if deadline passed
    ROUTING-ERROR if no route found

  See Also:
    RECEIVE-ENVELOPE, ROUTING-RESULT, CROSS-SWARM-ENVELOPE"))

(defgeneric receive-envelope (node envelope)
  (:documentation "Receive envelope at this node (local delivery).

  Called when an envelope's target swarm matches this node's ID. This is
  uncommon (most envelopes target specific leaves, not orchestrator nodes)
  but valid for meta-operations like:
    - Topology queries (\"list all children\")
    - Metrics aggregation (\"get stats from all leaves\")
    - Administrative commands (\"shutdown gracefully\")

  Args:
    node - SWARM-TREE instance
    envelope - CROSS-SWARM-ENVELOPE to receive

  Returns:
    Implementation-specific result (often NIL or acknowledgment).

  See Also:
    ROUTE-ENVELOPE"))

(defgeneric register-child (node child)
  (:documentation "Register a child node under this orchestrator.

  Adds a child to this SWARM-NODE and updates the routing table to reflect
  the new topology. If the child is a SWARM-NODE itself, its subtree routes
  should also be registered (cascading registration).

  This operation:
    1. Validates child is a SWARM-TREE instance
    2. Checks for ID conflicts (no duplicate child IDs)
    3. Sets child's parent to this node
    4. Adds child to children hash table
    5. Updates routing table with direct route
    6. If child is SWARM-NODE, imports its routing table

  Args:
    node - SWARM-NODE instance (parent)
    child - SWARM-TREE instance to register (leaf or node)

  Returns:
    The registered child.

  Raises:
    TYPE-ERROR if node is not SWARM-NODE
    ERROR if child ID already exists
    ERROR if child is NIL or invalid

  Side Effects:
    - Modifies node's children hash table
    - Updates routing table
    - Sets child's parent reference

  See Also:
    UNREGISTER-CHILD, GET-CHILD, LIST-CHILDREN"))

(defgeneric unregister-child (node child-id)
  (:documentation "Unregister a child node by ID.

  Removes a child from this SWARM-NODE and cleans up routing table entries
  that reference the child or its subtree.

  This operation:
    1. Validates child-id exists
    2. Retrieves child instance
    3. Clears child's parent reference
    4. Removes child from children hash table
    5. Removes routing table entries for child and subtree

  Args:
    node - SWARM-NODE instance
    child-id - String ID of child to remove

  Returns:
    The unregistered child instance, or NIL if child-id not found.

  Side Effects:
    - Modifies node's children hash table
    - Updates routing table
    - Clears child's parent reference

  See Also:
    REGISTER-CHILD, GET-CHILD"))

(defgeneric get-child (node child-id)
  (:documentation "Get child node by ID.

  Retrieves a child from this SWARM-NODE's children hash table.

  Args:
    node - SWARM-NODE instance
    child-id - String ID of child to retrieve

  Returns:
    SWARM-TREE instance if found, NIL otherwise.

  See Also:
    LIST-CHILDREN, REGISTER-CHILD"))

(defgeneric list-children (node)
  (:documentation "List all child nodes.

  Returns a list of all children registered under this SWARM-NODE.

  Args:
    node - SWARM-NODE instance

  Returns:
    List of SWARM-TREE instances (empty list if no children).

  See Also:
    GET-CHILD, REGISTER-CHILD"))

(defgeneric node-depth (node)
  (:documentation "Calculate depth of node in tree.

  Depth is defined as:
    - Root node (parent = NIL): depth 0
    - Direct child of root: depth 1
    - Grandchild of root: depth 2
    - etc.

  This is calculated by traversing up the tree until a root is reached.

  Args:
    node - SWARM-TREE instance

  Returns:
    Non-negative integer representing depth.

  Note:
    This operation is O(depth), which is typically small (2-4 levels).
    Circular parent references will cause infinite loops (not validated).

  See Also:
    PARENT-NODE"))

;;;; ============================================================================
;;;; Default Method Implementations
;;;; ============================================================================

(defmethod node-depth ((node swarm-tree))
  "Calculate depth by traversing up the tree to root.

  Default implementation for all SWARM-TREE instances."
  (if (parent-node node)
      (1+ (node-depth (parent-node node)))
      0))

(defmethod receive-envelope ((node swarm-tree) envelope)
  "Default receive implementation: log and discard.

  Subclasses should override if they need to handle local delivery."
  (declare (ignore envelope))
  (warn "RECEIVE-ENVELOPE not implemented for ~A (id: ~A)"
        (type-of node)
        (swarm-id node))
  nil)

;;;; For SWARM-LEAF, these operations are not supported
(defmethod register-child ((leaf swarm-leaf) child)
  "Leaf nodes cannot have children."
  (declare (ignore child))
  (error "Cannot register child on SWARM-LEAF (id: ~A). Leaves are terminal nodes."
         (swarm-id leaf)))

(defmethod unregister-child ((leaf swarm-leaf) child-id)
  "Leaf nodes cannot have children."
  (declare (ignore child-id))
  (error "Cannot unregister child on SWARM-LEAF (id: ~A). Leaves have no children."
         (swarm-id leaf)))

(defmethod get-child ((leaf swarm-leaf) child-id)
  "Leaf nodes have no children."
  (declare (ignore child-id))
  nil)

(defmethod list-children ((leaf swarm-leaf))
  "Leaf nodes have no children."
  nil)

;;;; For SWARM-NODE, implement child management
(defmethod register-child ((node swarm-node) (child swarm-tree))
  "Register a child swarm tree under this orchestrator node.

  Implementation for SWARM-NODE."
  (let ((child-id (swarm-id child)))
    ;; Check for duplicate ID
    (when (gethash child-id (node-children node))
      (error "Child with ID ~S already registered in node ~S"
             child-id (swarm-id node)))

    ;; Set parent reference
    (setf (parent-node child) node)

    ;; Add to children hash table
    (setf (gethash child-id (node-children node)) child)

    ;; TODO: Update routing table (requires routing package)
    ;; (add-route (routing-table node) child-id child-id)

    child))

(defmethod unregister-child ((node swarm-node) (child-id string))
  "Unregister a child by ID from this orchestrator node.

  Implementation for SWARM-NODE."
  (let ((child (gethash child-id (node-children node))))
    (when child
      ;; Clear parent reference
      (setf (parent-node child) nil)

      ;; Remove from children hash table
      (remhash child-id (node-children node))

      ;; TODO: Remove from routing table (requires routing package)
      ;; (remove-route (routing-table node) child-id)
      )
    child))

(defmethod get-child ((node swarm-node) (child-id string))
  "Get child by ID from this orchestrator node.

  Implementation for SWARM-NODE."
  (gethash child-id (node-children node)))

(defmethod list-children ((node swarm-node))
  "List all children of this orchestrator node.

  Implementation for SWARM-NODE."
  (loop for child being the hash-values of (node-children node)
        collect child))

;;;; ============================================================================
;;;; Helper Functions
;;;; ============================================================================

(defun make-swarm-leaf (id &key host port capabilities parent)
  "Create a SWARM-LEAF instance.

  This is a convenience constructor that provides defaults for common arguments.

  Args:
    id - Unique string identifier for this leaf (required)
    host - Hostname or IP of Python sw4rm instance (default: \"localhost\")
    port - gRPC port of Python sw4rm instance (default: 50051)
    capabilities - List of capability keywords (default: NIL)
    parent - Parent SWARM-NODE (default: NIL)

  Returns:
    New SWARM-LEAF instance.

  Examples:
    (make-swarm-leaf \"leaf-a\")
    (make-swarm-leaf \"frontend\" :host \"10.0.1.5\" :port 50052)
    (make-swarm-leaf \"backend\" :capabilities '(:nlp :tool-use))

  See Also:
    SWARM-LEAF, MAKE-SWARM-NODE"
  (make-instance 'swarm-leaf
                 :id id
                 :host (or host "localhost")
                 :port (or port 50051)
                 :capabilities capabilities
                 :parent parent))

(defun make-swarm-node (id &key policy parent)
  "Create a SWARM-NODE instance.

  This is a convenience constructor that provides defaults for common arguments.

  Args:
    id - Unique string identifier for this node (required)
    policy - Orchestration policy (default: NIL, uses global default)
    parent - Parent SWARM-NODE (default: NIL for root)

  Returns:
    New SWARM-NODE instance.

  Examples:
    (make-swarm-node \"root\")
    (make-swarm-node \"cluster-a\" :parent root-node)

  See Also:
    SWARM-NODE, MAKE-SWARM-LEAF"
  (make-instance 'swarm-node
                 :id id
                 :policy policy
                 :parent parent))

;;;; ============================================================================
;;;; Type Predicates
;;;; ============================================================================

(defun swarm-tree-p (object)
  "Check if object is a SWARM-TREE instance.

  Args:
    object - Any Lisp object

  Returns:
    T if object is a SWARM-TREE, NIL otherwise.

  See Also:
    SWARM-LEAF-P, SWARM-NODE-P"
  (typep object 'swarm-tree))

(defun swarm-leaf-p (object)
  "Check if object is a SWARM-LEAF instance.

  Args:
    object - Any Lisp object

  Returns:
    T if object is a SWARM-LEAF, NIL otherwise.

  See Also:
    SWARM-TREE-P, SWARM-NODE-P"
  (typep object 'swarm-leaf))

(defun swarm-node-p (object)
  "Check if object is a SWARM-NODE instance.

  Args:
    object - Any Lisp object

  Returns:
    T if object is a SWARM-NODE, NIL otherwise.

  See Also:
    SWARM-TREE-P, SWARM-LEAF-P"
  (typep object 'swarm-node))

;;;; ============================================================================
;;;; Print Methods for REPL Debugging
;;;; ============================================================================

(defmethod print-object ((node swarm-tree) stream)
  "Print human-readable representation of SWARM-TREE for REPL.

  Format: #<SWARM-TREE id=\"root\" status=:READY depth=0>"
  (print-unreadable-object (node stream :type t)
    (format stream "id=~S status=~S depth=~D"
            (swarm-id node)
            (node-status node)
            (node-depth node))))

(defmethod print-object ((leaf swarm-leaf) stream)
  "Print human-readable representation of SWARM-LEAF for REPL.

  Format: #<SWARM-LEAF id=\"leaf-a\" host=\"localhost\" port=50051 status=:READY>"
  (print-unreadable-object (leaf stream :type t)
    (format stream "id=~S host=~S port=~D status=~S"
            (swarm-id leaf)
            (leaf-host leaf)
            (leaf-port leaf)
            (node-status leaf))))

(defmethod print-object ((node swarm-node) stream)
  "Print human-readable representation of SWARM-NODE for REPL.

  Format: #<SWARM-NODE id=\"root\" children=3 depth=0 status=:READY>"
  (print-unreadable-object (node stream :type t)
    (format stream "id=~S children=~D depth=~D status=~S"
            (swarm-id node)
            (hash-table-count (node-children node))
            (node-depth node)
            (node-status node))))

;;;; End of file
