// Generated by scripts/generate_sdk_wire_contract.py --write.
export const protocolMethods = {
  "/sw4rm.activity.ActivityService/AppendArtifact": {
    "request": "sw4rm.activity.AppendArtifactRequest",
    "response": "sw4rm.activity.AppendArtifactResponse",
    "serverStreaming": false
  },
  "/sw4rm.activity.ActivityService/ListArtifacts": {
    "request": "sw4rm.activity.ListArtifactsRequest",
    "response": "sw4rm.activity.ListArtifactsResponse",
    "serverStreaming": false
  },
  "/sw4rm.connector.ConnectorService/RegisterProvider": {
    "request": "sw4rm.connector.ProviderRegisterRequest",
    "response": "sw4rm.connector.ProviderRegisterResponse",
    "serverStreaming": false
  },
  "/sw4rm.connector.ConnectorService/DescribeTools": {
    "request": "sw4rm.connector.DescribeToolsRequest",
    "response": "sw4rm.connector.DescribeToolsResponse",
    "serverStreaming": false
  },
  "/sw4rm.handoff.HandoffService/RequestHandoff": {
    "request": "sw4rm.handoff.HandoffRequest",
    "response": "sw4rm.common.Empty",
    "serverStreaming": false
  },
  "/sw4rm.handoff.HandoffService/AcceptHandoff": {
    "request": "sw4rm.handoff.HandoffResponse",
    "response": "sw4rm.common.Empty",
    "serverStreaming": false
  },
  "/sw4rm.handoff.HandoffService/RejectHandoff": {
    "request": "sw4rm.handoff.HandoffResponse",
    "response": "sw4rm.common.Empty",
    "serverStreaming": false
  },
  "/sw4rm.handoff.HandoffService/GetPendingHandoffs": {
    "request": "sw4rm.handoff.GetPendingHandoffsRequest",
    "response": "sw4rm.handoff.GetPendingHandoffsResponse",
    "serverStreaming": false
  },
  "/sw4rm.handoff.HandoffService/CompleteHandoff": {
    "request": "sw4rm.handoff.CompleteHandoffRequest",
    "response": "sw4rm.handoff.CompleteHandoffResponse",
    "serverStreaming": false
  },
  "/sw4rm.handoff.HandoffService/CancelDelegation": {
    "request": "sw4rm.handoff.CancelDelegation",
    "response": "sw4rm.handoff.CancelDelegationResponse",
    "serverStreaming": false
  },
  "/sw4rm.hitl.HitlService/Decide": {
    "request": "sw4rm.hitl.HitlInvocation",
    "response": "sw4rm.hitl.HitlDecision",
    "serverStreaming": false
  },
  "/sw4rm.logging.LoggingService/Ingest": {
    "request": "sw4rm.logging.LogEvent",
    "response": "sw4rm.logging.IngestResponse",
    "serverStreaming": false
  },
  "/sw4rm.negotiation.NegotiationService/Open": {
    "request": "sw4rm.negotiation.NegotiationOpen",
    "response": "sw4rm.common.Empty",
    "serverStreaming": false
  },
  "/sw4rm.negotiation.NegotiationService/Propose": {
    "request": "sw4rm.negotiation.Proposal",
    "response": "sw4rm.common.Empty",
    "serverStreaming": false
  },
  "/sw4rm.negotiation.NegotiationService/Counter": {
    "request": "sw4rm.negotiation.CounterProposal",
    "response": "sw4rm.common.Empty",
    "serverStreaming": false
  },
  "/sw4rm.negotiation.NegotiationService/Evaluate": {
    "request": "sw4rm.negotiation.Evaluation",
    "response": "sw4rm.common.Empty",
    "serverStreaming": false
  },
  "/sw4rm.negotiation.NegotiationService/Decide": {
    "request": "sw4rm.negotiation.Decision",
    "response": "sw4rm.common.Empty",
    "serverStreaming": false
  },
  "/sw4rm.negotiation.NegotiationService/Abort": {
    "request": "sw4rm.negotiation.AbortRequest",
    "response": "sw4rm.common.Empty",
    "serverStreaming": false
  },
  "/sw4rm.negotiation_room.NegotiationRoomService/SubmitProposal": {
    "request": "sw4rm.negotiation_room.SubmitProposalRequest",
    "response": "sw4rm.negotiation_room.SubmitProposalResponse",
    "serverStreaming": false
  },
  "/sw4rm.negotiation_room.NegotiationRoomService/SubmitVote": {
    "request": "sw4rm.negotiation_room.SubmitVoteRequest",
    "response": "sw4rm.negotiation_room.SubmitVoteResponse",
    "serverStreaming": false
  },
  "/sw4rm.negotiation_room.NegotiationRoomService/GetVotes": {
    "request": "sw4rm.negotiation_room.GetVotesRequest",
    "response": "sw4rm.negotiation_room.GetVotesResponse",
    "serverStreaming": false
  },
  "/sw4rm.negotiation_room.NegotiationRoomService/GetDecision": {
    "request": "sw4rm.negotiation_room.GetDecisionRequest",
    "response": "sw4rm.negotiation_room.GetDecisionResponse",
    "serverStreaming": false
  },
  "/sw4rm.negotiation_room.NegotiationRoomService/WaitForDecision": {
    "request": "sw4rm.negotiation_room.WaitForDecisionRequest",
    "response": "sw4rm.negotiation_room.WaitForDecisionResponse",
    "serverStreaming": false
  },
  "/sw4rm.reasoning.ReasoningProxy/CheckParallelism": {
    "request": "sw4rm.reasoning.ParallelismCheckRequest",
    "response": "sw4rm.reasoning.ParallelismCheckResponse",
    "serverStreaming": false
  },
  "/sw4rm.reasoning.ReasoningProxy/EvaluateDebate": {
    "request": "sw4rm.reasoning.DebateEvaluateRequest",
    "response": "sw4rm.reasoning.DebateEvaluateResponse",
    "serverStreaming": false
  },
  "/sw4rm.reasoning.ReasoningProxy/Summarize": {
    "request": "sw4rm.reasoning.SummarizeRequest",
    "response": "sw4rm.reasoning.SummarizeResponse",
    "serverStreaming": false
  },
  "/sw4rm.registry.RegistryService/RegisterAgent": {
    "request": "sw4rm.registry.RegisterAgentRequest",
    "response": "sw4rm.registry.RegisterAgentResponse",
    "serverStreaming": false
  },
  "/sw4rm.registry.RegistryService/Heartbeat": {
    "request": "sw4rm.registry.HeartbeatRequest",
    "response": "sw4rm.registry.HeartbeatResponse",
    "serverStreaming": false
  },
  "/sw4rm.registry.RegistryService/DeregisterAgent": {
    "request": "sw4rm.registry.DeregisterAgentRequest",
    "response": "sw4rm.registry.DeregisterAgentResponse",
    "serverStreaming": false
  },
  "/sw4rm.router.RouterService/SendMessage": {
    "request": "sw4rm.router.SendMessageRequest",
    "response": "sw4rm.router.SendMessageResponse",
    "serverStreaming": false
  },
  "/sw4rm.router.RouterService/StreamIncoming": {
    "request": "sw4rm.router.StreamRequest",
    "response": "sw4rm.router.StreamItem",
    "serverStreaming": true
  },
  "/sw4rm.router.RouterService/AckDelivery": {
    "request": "sw4rm.router.DeliveryAckRequest",
    "response": "sw4rm.router.DeliveryAckResponse",
    "serverStreaming": false
  },
  "/sw4rm.scheduler.SchedulerService/SubmitTask": {
    "request": "sw4rm.scheduler.SubmitTaskRequest",
    "response": "sw4rm.scheduler.SubmitTaskResponse",
    "serverStreaming": false
  },
  "/sw4rm.scheduler.SchedulerService/RequestPreemption": {
    "request": "sw4rm.scheduler.PreemptRequest",
    "response": "sw4rm.scheduler.PreemptResponse",
    "serverStreaming": false
  },
  "/sw4rm.scheduler.SchedulerService/ShutdownAgent": {
    "request": "sw4rm.scheduler.ShutdownAgentRequest",
    "response": "sw4rm.scheduler.ShutdownAgentResponse",
    "serverStreaming": false
  },
  "/sw4rm.scheduler.SchedulerService/PollActivityBuffer": {
    "request": "sw4rm.scheduler.PollActivityBufferRequest",
    "response": "sw4rm.scheduler.PollActivityBufferResponse",
    "serverStreaming": false
  },
  "/sw4rm.scheduler.SchedulerService/PurgeActivity": {
    "request": "sw4rm.scheduler.PurgeActivityRequest",
    "response": "sw4rm.scheduler.PurgeActivityResponse",
    "serverStreaming": false
  },
  "/sw4rm.scheduler.SchedulerPolicyService/SetNegotiationPolicy": {
    "request": "sw4rm.scheduler.SetNegotiationPolicyRequest",
    "response": "sw4rm.scheduler.SetNegotiationPolicyResponse",
    "serverStreaming": false
  },
  "/sw4rm.scheduler.SchedulerPolicyService/GetNegotiationPolicy": {
    "request": "sw4rm.scheduler.GetNegotiationPolicyRequest",
    "response": "sw4rm.scheduler.GetNegotiationPolicyResponse",
    "serverStreaming": false
  },
  "/sw4rm.scheduler.SchedulerPolicyService/SetPolicyProfiles": {
    "request": "sw4rm.scheduler.SetPolicyProfilesRequest",
    "response": "sw4rm.scheduler.SetPolicyProfilesResponse",
    "serverStreaming": false
  },
  "/sw4rm.scheduler.SchedulerPolicyService/ListPolicyProfiles": {
    "request": "sw4rm.scheduler.ListPolicyProfilesRequest",
    "response": "sw4rm.scheduler.ListPolicyProfilesResponse",
    "serverStreaming": false
  },
  "/sw4rm.scheduler.SchedulerPolicyService/GetEffectivePolicy": {
    "request": "sw4rm.scheduler.GetEffectivePolicyRequest",
    "response": "sw4rm.scheduler.GetEffectivePolicyResponse",
    "serverStreaming": false
  },
  "/sw4rm.scheduler.SchedulerPolicyService/SubmitEvaluation": {
    "request": "sw4rm.scheduler.SubmitEvaluationRequest",
    "response": "sw4rm.scheduler.SubmitEvaluationResponse",
    "serverStreaming": false
  },
  "/sw4rm.scheduler.SchedulerPolicyService/HitlAction": {
    "request": "sw4rm.scheduler.HitlActionRequest",
    "response": "sw4rm.scheduler.HitlActionResponse",
    "serverStreaming": false
  },
  "/sw4rm.tool.ToolService/Call": {
    "request": "sw4rm.tool.ToolCall",
    "response": "sw4rm.tool.ToolFrame",
    "serverStreaming": false
  },
  "/sw4rm.tool.ToolService/CallStream": {
    "request": "sw4rm.tool.ToolCall",
    "response": "sw4rm.tool.ToolFrame",
    "serverStreaming": true
  },
  "/sw4rm.tool.ToolService/Cancel": {
    "request": "sw4rm.tool.ToolCall",
    "response": "sw4rm.tool.ToolError",
    "serverStreaming": false
  },
  "/sw4rm.workflow.WorkflowService/CreateWorkflow": {
    "request": "sw4rm.workflow.CreateWorkflowRequest",
    "response": "sw4rm.workflow.CreateWorkflowResponse",
    "serverStreaming": false
  },
  "/sw4rm.workflow.WorkflowService/StartWorkflow": {
    "request": "sw4rm.workflow.StartWorkflowRequest",
    "response": "sw4rm.workflow.StartWorkflowResponse",
    "serverStreaming": false
  },
  "/sw4rm.workflow.WorkflowService/GetWorkflowState": {
    "request": "sw4rm.workflow.GetWorkflowStateRequest",
    "response": "sw4rm.workflow.GetWorkflowStateResponse",
    "serverStreaming": false
  },
  "/sw4rm.workflow.WorkflowService/ResumeWorkflow": {
    "request": "sw4rm.workflow.ResumeWorkflowRequest",
    "response": "sw4rm.workflow.ResumeWorkflowResponse",
    "serverStreaming": false
  },
  "/sw4rm.worktree.WorktreeService/Bind": {
    "request": "sw4rm.worktree.BindRequest",
    "response": "sw4rm.worktree.BindResponse",
    "serverStreaming": false
  },
  "/sw4rm.worktree.WorktreeService/Unbind": {
    "request": "sw4rm.worktree.UnbindRequest",
    "response": "sw4rm.worktree.UnbindResponse",
    "serverStreaming": false
  },
  "/sw4rm.worktree.WorktreeService/RequestSwitch": {
    "request": "sw4rm.worktree.SwitchRequest",
    "response": "sw4rm.worktree.StatusResponse",
    "serverStreaming": false
  },
  "/sw4rm.worktree.WorktreeService/ApproveSwitch": {
    "request": "sw4rm.worktree.SwitchApprove",
    "response": "sw4rm.worktree.StatusResponse",
    "serverStreaming": false
  },
  "/sw4rm.worktree.WorktreeService/RejectSwitch": {
    "request": "sw4rm.worktree.SwitchReject",
    "response": "sw4rm.worktree.StatusResponse",
    "serverStreaming": false
  },
  "/sw4rm.worktree.WorktreeService/Status": {
    "request": "sw4rm.worktree.StatusRequest",
    "response": "sw4rm.worktree.StatusResponse",
    "serverStreaming": false
  }
} as const;
export const protocolMessageFields = {
  "google.protobuf.Duration": [
    {
      "name": "seconds",
      "number": 1,
      "kind": "int64",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "nanos",
      "number": 2,
      "kind": "int32",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    }
  ],
  "google.protobuf.Timestamp": [
    {
      "name": "seconds",
      "number": 1,
      "kind": "int64",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "nanos",
      "number": 2,
      "kind": "int32",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.activity.AppendArtifactRequest": [
    {
      "name": "artifact",
      "number": 1,
      "kind": "message",
      "repeated": false,
      "target": "sw4rm.activity.Artifact",
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.activity.AppendArtifactResponse": [
    {
      "name": "ok",
      "number": 1,
      "kind": "bool",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "reason",
      "number": 2,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.activity.Artifact": [
    {
      "name": "negotiation_id",
      "number": 1,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "kind",
      "number": 2,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "version",
      "number": 3,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "content_type",
      "number": 4,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "content",
      "number": 5,
      "kind": "bytes",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "created_at",
      "number": 6,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.activity.ListArtifactsRequest": [
    {
      "name": "negotiation_id",
      "number": 1,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "kind",
      "number": 2,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.activity.ListArtifactsResponse": [
    {
      "name": "items",
      "number": 1,
      "kind": "message",
      "repeated": true,
      "target": "sw4rm.activity.Artifact",
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.common.Ack": [
    {
      "name": "ack_for_message_id",
      "number": 1,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "ack_stage",
      "number": 2,
      "kind": "enum",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": [
        "ACK_STAGE_UNSPECIFIED",
        "RECEIVED",
        "READ",
        "FULFILLED",
        "REJECTED",
        "FAILED",
        "TIMED_OUT"
      ]
    },
    {
      "name": "error_code",
      "number": 3,
      "kind": "enum",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": [
        "ERROR_CODE_UNSPECIFIED",
        "BUFFER_FULL",
        "NO_ROUTE",
        "ACK_TIMEOUT",
        "AGENT_UNAVAILABLE",
        "AGENT_SHUTDOWN",
        "VALIDATION_ERROR",
        "PERMISSION_DENIED",
        "UNSUPPORTED_MESSAGE_TYPE",
        "OVERSIZE_PAYLOAD",
        "TOOL_TIMEOUT",
        "PARTIAL_DELIVERY",
        "FORCED_PREEMPTION",
        "TTL_EXPIRED",
        "DUPLICATE_DETECTED",
        "ALREADY_IN_PROGRESS",
        "OVERLOADED",
        "REDIRECT",
        "INTERNAL_ERROR"
      ]
    },
    {
      "name": "note",
      "number": 4,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.common.Empty": [],
  "sw4rm.common.Envelope": [
    {
      "name": "message_id",
      "number": 1,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "idempotency_token",
      "number": 2,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "producer_id",
      "number": 3,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "correlation_id",
      "number": 4,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "sequence_number",
      "number": 5,
      "kind": "uint64",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "retry_count",
      "number": 6,
      "kind": "uint32",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "message_type",
      "number": 7,
      "kind": "enum",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": [
        "MESSAGE_TYPE_UNSPECIFIED",
        "CONTROL",
        "DATA",
        "HEARTBEAT",
        "NOTIFICATION",
        "ACKNOWLEDGEMENT",
        "HITL_INVOCATION",
        "WORKTREE_CONTROL",
        "NEGOTIATION",
        "TOOL_CALL",
        "TOOL_RESULT",
        "TOOL_ERROR"
      ]
    },
    {
      "name": "content_type",
      "number": 8,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "content_length",
      "number": 9,
      "kind": "uint64",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "repo_id",
      "number": 10,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "worktree_id",
      "number": 11,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "hlc_timestamp",
      "number": 12,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "ttl_ms",
      "number": 13,
      "kind": "uint64",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "timestamp",
      "number": 14,
      "kind": "message",
      "repeated": false,
      "target": "google.protobuf.Timestamp",
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "payload",
      "number": 15,
      "kind": "bytes",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "state",
      "number": 16,
      "kind": "enum",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": [
        "ENVELOPE_STATE_UNSPECIFIED",
        "ENVELOPE_STATE_SENT",
        "ENVELOPE_STATE_RECEIVED",
        "ENVELOPE_STATE_READ",
        "ENVELOPE_STATE_FULFILLED",
        "ENVELOPE_STATE_REJECTED",
        "ENVELOPE_STATE_FAILED",
        "ENVELOPE_STATE_TIMED_OUT"
      ]
    },
    {
      "name": "parent_correlation_id",
      "number": 100,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.connector.DescribeToolsRequest": [
    {
      "name": "provider_id",
      "number": 1,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.connector.DescribeToolsResponse": [
    {
      "name": "tools",
      "number": 1,
      "kind": "message",
      "repeated": true,
      "target": "sw4rm.connector.ToolDescriptor",
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.connector.ProviderRegisterRequest": [
    {
      "name": "provider_id",
      "number": 1,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "tools",
      "number": 2,
      "kind": "message",
      "repeated": true,
      "target": "sw4rm.connector.ToolDescriptor",
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.connector.ProviderRegisterResponse": [
    {
      "name": "ok",
      "number": 1,
      "kind": "bool",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "reason",
      "number": 2,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.connector.ToolDescriptor": [
    {
      "name": "tool_name",
      "number": 1,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "input_schema",
      "number": 2,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "output_schema",
      "number": 3,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "idempotent",
      "number": 4,
      "kind": "bool",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "needs_worktree",
      "number": 5,
      "kind": "bool",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "default_timeout_s",
      "number": 6,
      "kind": "uint32",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "max_concurrency",
      "number": 7,
      "kind": "uint32",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "side_effects",
      "number": 8,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.handoff.BudgetEnvelope": [
    {
      "name": "token_budget_remaining",
      "number": 1,
      "kind": "uint64",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "wall_time_remaining_ms",
      "number": 2,
      "kind": "uint64",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "deadline_epoch_ms",
      "number": 3,
      "kind": "uint64",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "current_depth",
      "number": 4,
      "kind": "uint32",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "max_delegation_depth",
      "number": 5,
      "kind": "uint32",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.handoff.CancelDelegation": [
    {
      "name": "correlation_id",
      "number": 1,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "reason",
      "number": 2,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "grace_period_ms",
      "number": 3,
      "kind": "uint64",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.handoff.CancelDelegationResponse": [
    {
      "name": "acknowledged",
      "number": 1,
      "kind": "bool",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "message",
      "number": 2,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.handoff.CompleteHandoffRequest": [
    {
      "name": "request_id",
      "number": 1,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "status",
      "number": 2,
      "kind": "enum",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": [
        "HANDOFF_STATUS_UNSPECIFIED",
        "PENDING",
        "ACCEPTED",
        "REJECTED",
        "COMPLETED",
        "EXPIRED"
      ]
    }
  ],
  "sw4rm.handoff.CompleteHandoffResponse": [
    {
      "name": "success",
      "number": 1,
      "kind": "bool",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "message",
      "number": 2,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.handoff.GetPendingHandoffsRequest": [
    {
      "name": "agent_id",
      "number": 1,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.handoff.GetPendingHandoffsResponse": [
    {
      "name": "pending_requests",
      "number": 1,
      "kind": "message",
      "repeated": true,
      "target": "sw4rm.handoff.HandoffRequest",
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.handoff.HandoffRequest": [
    {
      "name": "request_id",
      "number": 1,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "from_agent",
      "number": 2,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "to_agent",
      "number": 3,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "reason",
      "number": 4,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "context_snapshot",
      "number": 5,
      "kind": "bytes",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "capabilities_required",
      "number": 6,
      "kind": "string",
      "repeated": true,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "priority",
      "number": 7,
      "kind": "int32",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "timeout",
      "number": 8,
      "kind": "message",
      "repeated": false,
      "target": "google.protobuf.Duration",
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "budget",
      "number": 100,
      "kind": "message",
      "repeated": false,
      "target": "sw4rm.handoff.BudgetEnvelope",
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "delegation_policy",
      "number": 101,
      "kind": "message",
      "repeated": false,
      "target": "sw4rm.handoff.SwarmDelegationPolicy",
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.handoff.HandoffResponse": [
    {
      "name": "request_id",
      "number": 1,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "accepted",
      "number": 2,
      "kind": "bool",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "accepting_agent",
      "number": 3,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "rejection_reason",
      "number": 4,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "rejection_code",
      "number": 100,
      "kind": "enum",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": [
        "ERROR_CODE_UNSPECIFIED",
        "BUFFER_FULL",
        "NO_ROUTE",
        "ACK_TIMEOUT",
        "AGENT_UNAVAILABLE",
        "AGENT_SHUTDOWN",
        "VALIDATION_ERROR",
        "PERMISSION_DENIED",
        "UNSUPPORTED_MESSAGE_TYPE",
        "OVERSIZE_PAYLOAD",
        "TOOL_TIMEOUT",
        "PARTIAL_DELIVERY",
        "FORCED_PREEMPTION",
        "TTL_EXPIRED",
        "DUPLICATE_DETECTED",
        "ALREADY_IN_PROGRESS",
        "OVERLOADED",
        "REDIRECT",
        "INTERNAL_ERROR"
      ]
    },
    {
      "name": "retry_after_ms",
      "number": 101,
      "kind": "uint64",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "redirect_to_agent_id",
      "number": 110,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.handoff.SwarmDelegationPolicy": [
    {
      "name": "max_retries_on_overloaded",
      "number": 1,
      "kind": "uint32",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "initial_backoff_ms",
      "number": 2,
      "kind": "uint64",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "backoff_multiplier",
      "number": 3,
      "kind": "double",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "max_backoff_ms",
      "number": 4,
      "kind": "uint64",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "allow_spillover_routing",
      "number": 5,
      "kind": "bool",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "max_redirects",
      "number": 6,
      "kind": "uint32",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.hitl.HitlDecision": [
    {
      "name": "action",
      "number": 1,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "decision_payload",
      "number": 2,
      "kind": "bytes",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "rationale",
      "number": 3,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.hitl.HitlInvocation": [
    {
      "name": "reason_type",
      "number": 1,
      "kind": "enum",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": [
        "HITL_REASON_UNSPECIFIED",
        "CONFLICT",
        "SECURITY_APPROVAL",
        "TASK_ESCALATION",
        "MANUAL_OVERRIDE",
        "WORKTREE_OVERRIDE",
        "DEBATE_DEADLOCK",
        "TOOL_PRIVILEGE_ESCALATION",
        "CONNECTOR_APPROVAL"
      ]
    },
    {
      "name": "context",
      "number": 2,
      "kind": "bytes",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "proposed_actions",
      "number": 3,
      "kind": "string",
      "repeated": true,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "priority",
      "number": 4,
      "kind": "int32",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.logging.IngestResponse": [
    {
      "name": "ok",
      "number": 1,
      "kind": "bool",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.logging.LogEvent": [
    {
      "name": "ts",
      "number": 1,
      "kind": "message",
      "repeated": false,
      "target": "google.protobuf.Timestamp",
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "correlation_id",
      "number": 2,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "agent_id",
      "number": 3,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "event_type",
      "number": 4,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "level",
      "number": 5,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "details_json",
      "number": 6,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.negotiation.AbortRequest": [
    {
      "name": "negotiation_id",
      "number": 1,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "reason",
      "number": 2,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.negotiation.CounterProposal": [
    {
      "name": "negotiation_id",
      "number": 1,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "from_agent",
      "number": 2,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "content_type",
      "number": 3,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "payload",
      "number": 4,
      "kind": "bytes",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.negotiation.Decision": [
    {
      "name": "negotiation_id",
      "number": 1,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "decided_by",
      "number": 2,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "content_type",
      "number": 3,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "result",
      "number": 4,
      "kind": "bytes",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.negotiation.Evaluation": [
    {
      "name": "negotiation_id",
      "number": 1,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "from_agent",
      "number": 2,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "confidence_score",
      "number": 3,
      "kind": "double",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "notes",
      "number": 4,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.negotiation.NegotiationOpen": [
    {
      "name": "negotiation_id",
      "number": 1,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "correlation_id",
      "number": 2,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "topic",
      "number": 3,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "participants",
      "number": 4,
      "kind": "string",
      "repeated": true,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "intensity",
      "number": 5,
      "kind": "enum",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": [
        "DEBATE_INTENSITY_UNSPECIFIED",
        "LOWEST",
        "LOW",
        "MEDIUM",
        "HIGH",
        "HIGHEST"
      ]
    },
    {
      "name": "debate_timeout",
      "number": 6,
      "kind": "message",
      "repeated": false,
      "target": "google.protobuf.Duration",
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.negotiation.Proposal": [
    {
      "name": "negotiation_id",
      "number": 1,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "from_agent",
      "number": 2,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "content_type",
      "number": 3,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "payload",
      "number": 4,
      "kind": "bytes",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.negotiation_room.AggregatedScore": [
    {
      "name": "mean",
      "number": 1,
      "kind": "double",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "min_score",
      "number": 2,
      "kind": "double",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "max_score",
      "number": 3,
      "kind": "double",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "std_dev",
      "number": 4,
      "kind": "double",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "weighted_mean",
      "number": 5,
      "kind": "double",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "vote_count",
      "number": 6,
      "kind": "int32",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.negotiation_room.GetDecisionRequest": [
    {
      "name": "artifact_id",
      "number": 1,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "negotiation_room_id",
      "number": 2,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.negotiation_room.GetDecisionResponse": [
    {
      "name": "decision",
      "number": 1,
      "kind": "message",
      "repeated": false,
      "target": "sw4rm.negotiation_room.NegotiationDecision",
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.negotiation_room.GetVotesRequest": [
    {
      "name": "artifact_id",
      "number": 1,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "negotiation_room_id",
      "number": 2,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.negotiation_room.GetVotesResponse": [
    {
      "name": "votes",
      "number": 1,
      "kind": "message",
      "repeated": true,
      "target": "sw4rm.negotiation_room.NegotiationVote",
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "vote_count",
      "number": 2,
      "kind": "int32",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.negotiation_room.NegotiationDecision": [
    {
      "name": "artifact_id",
      "number": 1,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "outcome",
      "number": 2,
      "kind": "enum",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": [
        "DECISION_OUTCOME_UNSPECIFIED",
        "APPROVED",
        "REVISION_REQUESTED",
        "ESCALATED_TO_HITL"
      ]
    },
    {
      "name": "votes",
      "number": 3,
      "kind": "message",
      "repeated": true,
      "target": "sw4rm.negotiation_room.NegotiationVote",
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "aggregated_score",
      "number": 4,
      "kind": "message",
      "repeated": false,
      "target": "sw4rm.negotiation_room.AggregatedScore",
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "policy_version",
      "number": 5,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "reason",
      "number": 6,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "negotiation_room_id",
      "number": 7,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "decided_at",
      "number": 8,
      "kind": "message",
      "repeated": false,
      "target": "google.protobuf.Timestamp",
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.negotiation_room.NegotiationProposal": [
    {
      "name": "artifact_type",
      "number": 1,
      "kind": "enum",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": [
        "ARTIFACT_TYPE_UNSPECIFIED",
        "REQUIREMENTS",
        "PLAN",
        "CODE",
        "DEPLOYMENT"
      ]
    },
    {
      "name": "artifact_id",
      "number": 2,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "producer_id",
      "number": 3,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "artifact",
      "number": 4,
      "kind": "bytes",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "artifact_content_type",
      "number": 5,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "requested_critics",
      "number": 6,
      "kind": "string",
      "repeated": true,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "negotiation_room_id",
      "number": 7,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "created_at",
      "number": 8,
      "kind": "message",
      "repeated": false,
      "target": "google.protobuf.Timestamp",
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.negotiation_room.NegotiationVote": [
    {
      "name": "artifact_id",
      "number": 1,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "critic_id",
      "number": 2,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "score",
      "number": 3,
      "kind": "double",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "confidence",
      "number": 4,
      "kind": "double",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "passed",
      "number": 5,
      "kind": "bool",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "strengths",
      "number": 6,
      "kind": "string",
      "repeated": true,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "weaknesses",
      "number": 7,
      "kind": "string",
      "repeated": true,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "recommendations",
      "number": 8,
      "kind": "string",
      "repeated": true,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "negotiation_room_id",
      "number": 9,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "voted_at",
      "number": 10,
      "kind": "message",
      "repeated": false,
      "target": "google.protobuf.Timestamp",
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.negotiation_room.SubmitProposalRequest": [
    {
      "name": "proposal",
      "number": 1,
      "kind": "message",
      "repeated": false,
      "target": "sw4rm.negotiation_room.NegotiationProposal",
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.negotiation_room.SubmitProposalResponse": [
    {
      "name": "artifact_id",
      "number": 1,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "negotiation_room_id",
      "number": 2,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.negotiation_room.SubmitVoteRequest": [
    {
      "name": "vote",
      "number": 1,
      "kind": "message",
      "repeated": false,
      "target": "sw4rm.negotiation_room.NegotiationVote",
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.negotiation_room.SubmitVoteResponse": [
    {
      "name": "artifact_id",
      "number": 1,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "critic_id",
      "number": 2,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.negotiation_room.WaitForDecisionRequest": [
    {
      "name": "artifact_id",
      "number": 1,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "negotiation_room_id",
      "number": 2,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "timeout_seconds",
      "number": 3,
      "kind": "uint32",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.negotiation_room.WaitForDecisionResponse": [
    {
      "name": "decision",
      "number": 1,
      "kind": "message",
      "repeated": false,
      "target": "sw4rm.negotiation_room.NegotiationDecision",
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.policy.AgentPreferences": [
    {
      "name": "max_rounds",
      "number": 1,
      "kind": "uint32",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "score_threshold",
      "number": 2,
      "kind": "float",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "diff_tolerance",
      "number": 3,
      "kind": "float",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "round_timeout_ms",
      "number": 4,
      "kind": "uint64",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "token_budget_per_round",
      "number": 5,
      "kind": "uint64",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "total_token_budget",
      "number": 6,
      "kind": "uint64",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "oscillation_limit",
      "number": 7,
      "kind": "uint32",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.policy.DecisionReport": [
    {
      "name": "decided_by",
      "number": 1,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "final_score",
      "number": 2,
      "kind": "float",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "rationale",
      "number": 3,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "stop_reason",
      "number": 4,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.policy.DeltaSummary": [
    {
      "name": "magnitude",
      "number": 1,
      "kind": "float",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "changed_paths",
      "number": 2,
      "kind": "string",
      "repeated": true,
      "target": null,
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.policy.EffectivePolicy": [
    {
      "name": "policy",
      "number": 1,
      "kind": "message",
      "repeated": false,
      "target": "sw4rm.policy.NegotiationPolicy",
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "applied",
      "number": 2,
      "kind": "message",
      "repeated": true,
      "target": "sw4rm.policy.EffectivePolicy.AppliedEntry",
      "map_entry": true,
      "enum_values": []
    }
  ],
  "sw4rm.policy.EffectivePolicy.AppliedEntry": [
    {
      "name": "key",
      "number": 1,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "value",
      "number": 2,
      "kind": "message",
      "repeated": false,
      "target": "sw4rm.policy.AgentPreferences",
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.policy.EvaluationReport": [
    {
      "name": "from_agent",
      "number": 1,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "deterministic_score",
      "number": 2,
      "kind": "float",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "llm_confidence",
      "number": 3,
      "kind": "float",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "notes",
      "number": 4,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "delta",
      "number": 5,
      "kind": "message",
      "repeated": false,
      "target": "sw4rm.policy.DeltaSummary",
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.policy.NegotiationPolicy": [
    {
      "name": "max_rounds",
      "number": 1,
      "kind": "uint32",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "score_threshold",
      "number": 2,
      "kind": "float",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "diff_tolerance",
      "number": 3,
      "kind": "float",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "round_timeout_ms",
      "number": 4,
      "kind": "uint64",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "token_budget_per_round",
      "number": 5,
      "kind": "uint64",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "total_token_budget",
      "number": 6,
      "kind": "uint64",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "oscillation_limit",
      "number": 7,
      "kind": "uint32",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "hitl",
      "number": 8,
      "kind": "message",
      "repeated": false,
      "target": "sw4rm.policy.NegotiationPolicy.Hitl",
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "scoring",
      "number": 9,
      "kind": "message",
      "repeated": false,
      "target": "sw4rm.policy.NegotiationPolicy.Scoring",
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.policy.NegotiationPolicy.Hitl": [
    {
      "name": "mode",
      "number": 1,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.policy.NegotiationPolicy.Scoring": [
    {
      "name": "require_schema_valid",
      "number": 1,
      "kind": "bool",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "require_examples_pass",
      "number": 2,
      "kind": "bool",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "llm_weight",
      "number": 3,
      "kind": "float",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.policy.PolicyProfile": [
    {
      "name": "name",
      "number": 1,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "policy",
      "number": 2,
      "kind": "message",
      "repeated": false,
      "target": "sw4rm.policy.NegotiationPolicy",
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.reasoning.DebateEvaluateRequest": [
    {
      "name": "negotiation_id",
      "number": 1,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "proposal_a",
      "number": 2,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "proposal_b",
      "number": 3,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "intensity",
      "number": 4,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.reasoning.DebateEvaluateResponse": [
    {
      "name": "confidence_score",
      "number": 1,
      "kind": "double",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "notes",
      "number": 2,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.reasoning.ParallelismCheckRequest": [
    {
      "name": "scope_a",
      "number": 1,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "scope_b",
      "number": 2,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.reasoning.ParallelismCheckResponse": [
    {
      "name": "confidence_score",
      "number": 1,
      "kind": "double",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "notes",
      "number": 2,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.reasoning.SummarizeRequest": [
    {
      "name": "session_id",
      "number": 1,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "segments",
      "number": 2,
      "kind": "message",
      "repeated": true,
      "target": "sw4rm.reasoning.TextSegment",
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "max_tokens",
      "number": 3,
      "kind": "uint32",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "mode",
      "number": 4,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.reasoning.SummarizeResponse": [
    {
      "name": "summary",
      "number": 1,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "tokens",
      "number": 2,
      "kind": "uint32",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "cost_cents",
      "number": 3,
      "kind": "double",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "model",
      "number": 4,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.reasoning.TextSegment": [
    {
      "name": "kind",
      "number": 1,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "content",
      "number": 2,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "seq",
      "number": 3,
      "kind": "int64",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "at",
      "number": 4,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.registry.AgentDescriptor": [
    {
      "name": "agent_id",
      "number": 1,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "name",
      "number": 2,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "description",
      "number": 3,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "capabilities",
      "number": 4,
      "kind": "string",
      "repeated": true,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "communication_class",
      "number": 5,
      "kind": "enum",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": [
        "COMM_CLASS_UNSPECIFIED",
        "PRIVILEGED",
        "STANDARD",
        "BULK"
      ]
    },
    {
      "name": "modalities_supported",
      "number": 6,
      "kind": "string",
      "repeated": true,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "reasoning_connectors",
      "number": 7,
      "kind": "string",
      "repeated": true,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "public_key",
      "number": 8,
      "kind": "bytes",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "registration_type",
      "number": 100,
      "kind": "enum",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": [
        "REGISTRATION_TYPE_UNSPECIFIED",
        "STANDARD_AGENT",
        "SWARM_GATEWAY"
      ]
    },
    {
      "name": "max_concurrent_delegations",
      "number": 101,
      "kind": "uint32",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.registry.DeregisterAgentRequest": [
    {
      "name": "agent_id",
      "number": 1,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "reason",
      "number": 2,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.registry.DeregisterAgentResponse": [
    {
      "name": "ok",
      "number": 1,
      "kind": "bool",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.registry.HeartbeatRequest": [
    {
      "name": "agent_id",
      "number": 1,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "state",
      "number": 2,
      "kind": "enum",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": [
        "AGENT_STATE_UNSPECIFIED",
        "INITIALIZING",
        "RUNNABLE",
        "SCHEDULED",
        "RUNNING",
        "WAITING",
        "WAITING_RESOURCES",
        "SUSPENDED",
        "RESUMED",
        "COMPLETED",
        "FAILED_STATE",
        "SHUTTING_DOWN",
        "RECOVERING"
      ]
    },
    {
      "name": "health",
      "number": 3,
      "kind": "message",
      "repeated": true,
      "target": "sw4rm.registry.HeartbeatRequest.HealthEntry",
      "map_entry": true,
      "enum_values": []
    }
  ],
  "sw4rm.registry.HeartbeatRequest.HealthEntry": [
    {
      "name": "key",
      "number": 1,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "value",
      "number": 2,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.registry.HeartbeatResponse": [
    {
      "name": "ok",
      "number": 1,
      "kind": "bool",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.registry.RegisterAgentRequest": [
    {
      "name": "agent",
      "number": 1,
      "kind": "message",
      "repeated": false,
      "target": "sw4rm.registry.AgentDescriptor",
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.registry.RegisterAgentResponse": [
    {
      "name": "accepted",
      "number": 1,
      "kind": "bool",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "reason",
      "number": 2,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.router.DeliveryAckRequest": [
    {
      "name": "agent_id",
      "number": 1,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "seq",
      "number": 2,
      "kind": "int64",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "message_id",
      "number": 3,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "outcome",
      "number": 4,
      "kind": "enum",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": [
        "DELIVERY_ACK_OUTCOME_DELIVERED",
        "DELIVERY_ACK_OUTCOME_PERMANENT_FAILURE"
      ]
    }
  ],
  "sw4rm.router.DeliveryAckResponse": [
    {
      "name": "recorded",
      "number": 1,
      "kind": "bool",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.router.SendMessageRequest": [
    {
      "name": "msg",
      "number": 1,
      "kind": "message",
      "repeated": false,
      "target": "sw4rm.common.Envelope",
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.router.SendMessageResponse": [
    {
      "name": "accepted",
      "number": 1,
      "kind": "bool",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "reason",
      "number": 2,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.router.StreamItem": [
    {
      "name": "msg",
      "number": 1,
      "kind": "message",
      "repeated": false,
      "target": "sw4rm.common.Envelope",
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "seq",
      "number": 2,
      "kind": "int64",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.router.StreamRequest": [
    {
      "name": "agent_id",
      "number": 1,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.scheduler.ActivityEntry": [
    {
      "name": "task_id",
      "number": 1,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "repo_id",
      "number": 2,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "worktree_id",
      "number": 3,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "branch",
      "number": 4,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "description",
      "number": 5,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "timestamp",
      "number": 6,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.scheduler.GetEffectivePolicyRequest": [
    {
      "name": "negotiation_id",
      "number": 1,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.scheduler.GetEffectivePolicyResponse": [
    {
      "name": "effective",
      "number": 1,
      "kind": "message",
      "repeated": false,
      "target": "sw4rm.policy.EffectivePolicy",
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.scheduler.GetNegotiationPolicyRequest": [],
  "sw4rm.scheduler.GetNegotiationPolicyResponse": [
    {
      "name": "policy",
      "number": 1,
      "kind": "message",
      "repeated": false,
      "target": "sw4rm.policy.NegotiationPolicy",
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.scheduler.HitlActionRequest": [
    {
      "name": "negotiation_id",
      "number": 1,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "action",
      "number": 2,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "rationale",
      "number": 3,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.scheduler.HitlActionResponse": [
    {
      "name": "ok",
      "number": 1,
      "kind": "bool",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "reason",
      "number": 2,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.scheduler.ListPolicyProfilesRequest": [],
  "sw4rm.scheduler.ListPolicyProfilesResponse": [
    {
      "name": "profiles",
      "number": 1,
      "kind": "message",
      "repeated": true,
      "target": "sw4rm.policy.PolicyProfile",
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.scheduler.PollActivityBufferRequest": [
    {
      "name": "agent_id",
      "number": 1,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.scheduler.PollActivityBufferResponse": [
    {
      "name": "entries",
      "number": 1,
      "kind": "message",
      "repeated": true,
      "target": "sw4rm.scheduler.ActivityEntry",
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.scheduler.PreemptRequest": [
    {
      "name": "agent_id",
      "number": 1,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "task_id",
      "number": 2,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "reason",
      "number": 3,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.scheduler.PreemptResponse": [
    {
      "name": "enqueued",
      "number": 1,
      "kind": "bool",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.scheduler.PurgeActivityRequest": [
    {
      "name": "agent_id",
      "number": 1,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "task_ids",
      "number": 2,
      "kind": "string",
      "repeated": true,
      "target": null,
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.scheduler.PurgeActivityResponse": [
    {
      "name": "purged",
      "number": 1,
      "kind": "uint32",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.scheduler.SetNegotiationPolicyRequest": [
    {
      "name": "policy",
      "number": 1,
      "kind": "message",
      "repeated": false,
      "target": "sw4rm.policy.NegotiationPolicy",
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.scheduler.SetNegotiationPolicyResponse": [
    {
      "name": "ok",
      "number": 1,
      "kind": "bool",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "reason",
      "number": 2,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.scheduler.SetPolicyProfilesRequest": [
    {
      "name": "profiles",
      "number": 1,
      "kind": "message",
      "repeated": true,
      "target": "sw4rm.policy.PolicyProfile",
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.scheduler.SetPolicyProfilesResponse": [
    {
      "name": "ok",
      "number": 1,
      "kind": "bool",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "reason",
      "number": 2,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.scheduler.ShutdownAgentRequest": [
    {
      "name": "agent_id",
      "number": 1,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "grace_period",
      "number": 2,
      "kind": "message",
      "repeated": false,
      "target": "google.protobuf.Duration",
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.scheduler.ShutdownAgentResponse": [
    {
      "name": "ok",
      "number": 1,
      "kind": "bool",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.scheduler.SubmitEvaluationRequest": [
    {
      "name": "negotiation_id",
      "number": 1,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "report",
      "number": 2,
      "kind": "message",
      "repeated": false,
      "target": "sw4rm.policy.EvaluationReport",
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.scheduler.SubmitEvaluationResponse": [
    {
      "name": "accepted",
      "number": 1,
      "kind": "bool",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "reason",
      "number": 2,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.scheduler.SubmitTaskRequest": [
    {
      "name": "agent_id",
      "number": 1,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "task_id",
      "number": 2,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "priority",
      "number": 3,
      "kind": "int32",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "params",
      "number": 4,
      "kind": "bytes",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "content_type",
      "number": 5,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "scope",
      "number": 6,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.scheduler.SubmitTaskResponse": [
    {
      "name": "accepted",
      "number": 1,
      "kind": "bool",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "reason",
      "number": 2,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.tool.ExecutionPolicy": [
    {
      "name": "timeout",
      "number": 1,
      "kind": "message",
      "repeated": false,
      "target": "google.protobuf.Duration",
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "max_retries",
      "number": 2,
      "kind": "uint32",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "backoff",
      "number": 3,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "worktree_required",
      "number": 4,
      "kind": "bool",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "network_policy",
      "number": 5,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "privilege_level",
      "number": 6,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "budget_cpu_ms",
      "number": 7,
      "kind": "uint64",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "budget_wall_ms",
      "number": 8,
      "kind": "uint64",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.tool.ToolCall": [
    {
      "name": "call_id",
      "number": 1,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "tool_name",
      "number": 2,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "provider_id",
      "number": 3,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "content_type",
      "number": 4,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "args",
      "number": 5,
      "kind": "bytes",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "policy",
      "number": 6,
      "kind": "message",
      "repeated": false,
      "target": "sw4rm.tool.ExecutionPolicy",
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "stream",
      "number": 7,
      "kind": "bool",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.tool.ToolError": [
    {
      "name": "call_id",
      "number": 1,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "error_code",
      "number": 2,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "message",
      "number": 3,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.tool.ToolFrame": [
    {
      "name": "call_id",
      "number": 1,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "frame_no",
      "number": 2,
      "kind": "uint64",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "final",
      "number": 3,
      "kind": "bool",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "content_type",
      "number": 4,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "data",
      "number": 5,
      "kind": "bytes",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "summary",
      "number": 6,
      "kind": "bytes",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.workflow.CreateWorkflowRequest": [
    {
      "name": "definition",
      "number": 1,
      "kind": "message",
      "repeated": false,
      "target": "sw4rm.workflow.WorkflowDefinition",
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.workflow.CreateWorkflowResponse": [
    {
      "name": "workflow_id",
      "number": 1,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "success",
      "number": 2,
      "kind": "bool",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "error",
      "number": 3,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.workflow.GetWorkflowStateRequest": [
    {
      "name": "workflow_id",
      "number": 1,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.workflow.GetWorkflowStateResponse": [
    {
      "name": "state",
      "number": 1,
      "kind": "message",
      "repeated": false,
      "target": "sw4rm.workflow.WorkflowState",
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "success",
      "number": 2,
      "kind": "bool",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "error",
      "number": 3,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.workflow.NodeState": [
    {
      "name": "node_id",
      "number": 1,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "status",
      "number": 2,
      "kind": "enum",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": [
        "NODE_STATUS_UNSPECIFIED",
        "PENDING",
        "READY",
        "RUNNING",
        "COMPLETED",
        "FAILED",
        "SKIPPED"
      ]
    },
    {
      "name": "started_at",
      "number": 3,
      "kind": "message",
      "repeated": false,
      "target": "google.protobuf.Timestamp",
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "completed_at",
      "number": 4,
      "kind": "message",
      "repeated": false,
      "target": "google.protobuf.Timestamp",
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "output",
      "number": 5,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "error",
      "number": 6,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.workflow.ResumeWorkflowRequest": [
    {
      "name": "workflow_id",
      "number": 1,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "node_id",
      "number": 2,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "workflow_data",
      "number": 3,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "metadata",
      "number": 4,
      "kind": "message",
      "repeated": true,
      "target": "sw4rm.workflow.ResumeWorkflowRequest.MetadataEntry",
      "map_entry": true,
      "enum_values": []
    }
  ],
  "sw4rm.workflow.ResumeWorkflowRequest.MetadataEntry": [
    {
      "name": "key",
      "number": 1,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "value",
      "number": 2,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.workflow.ResumeWorkflowResponse": [
    {
      "name": "workflow_id",
      "number": 1,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "state",
      "number": 2,
      "kind": "message",
      "repeated": false,
      "target": "sw4rm.workflow.WorkflowState",
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "success",
      "number": 3,
      "kind": "bool",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "error",
      "number": 4,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.workflow.StartWorkflowRequest": [
    {
      "name": "workflow_id",
      "number": 1,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "workflow_data",
      "number": 2,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "metadata",
      "number": 3,
      "kind": "message",
      "repeated": true,
      "target": "sw4rm.workflow.StartWorkflowRequest.MetadataEntry",
      "map_entry": true,
      "enum_values": []
    }
  ],
  "sw4rm.workflow.StartWorkflowRequest.MetadataEntry": [
    {
      "name": "key",
      "number": 1,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "value",
      "number": 2,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.workflow.StartWorkflowResponse": [
    {
      "name": "workflow_id",
      "number": 1,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "state",
      "number": 2,
      "kind": "message",
      "repeated": false,
      "target": "sw4rm.workflow.WorkflowState",
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "success",
      "number": 3,
      "kind": "bool",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "error",
      "number": 4,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.workflow.WorkflowDefinition": [
    {
      "name": "workflow_id",
      "number": 1,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "nodes",
      "number": 2,
      "kind": "message",
      "repeated": true,
      "target": "sw4rm.workflow.WorkflowDefinition.NodesEntry",
      "map_entry": true,
      "enum_values": []
    },
    {
      "name": "created_at",
      "number": 3,
      "kind": "message",
      "repeated": false,
      "target": "google.protobuf.Timestamp",
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "metadata",
      "number": 4,
      "kind": "message",
      "repeated": true,
      "target": "sw4rm.workflow.WorkflowDefinition.MetadataEntry",
      "map_entry": true,
      "enum_values": []
    }
  ],
  "sw4rm.workflow.WorkflowDefinition.MetadataEntry": [
    {
      "name": "key",
      "number": 1,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "value",
      "number": 2,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.workflow.WorkflowDefinition.NodesEntry": [
    {
      "name": "key",
      "number": 1,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "value",
      "number": 2,
      "kind": "message",
      "repeated": false,
      "target": "sw4rm.workflow.WorkflowNode",
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.workflow.WorkflowNode": [
    {
      "name": "node_id",
      "number": 1,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "agent_id",
      "number": 2,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "dependencies",
      "number": 3,
      "kind": "string",
      "repeated": true,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "trigger_type",
      "number": 4,
      "kind": "enum",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": [
        "TRIGGER_TYPE_UNSPECIFIED",
        "EVENT",
        "SCHEDULE",
        "MANUAL",
        "DEPENDENCY"
      ]
    },
    {
      "name": "input_mapping",
      "number": 5,
      "kind": "message",
      "repeated": true,
      "target": "sw4rm.workflow.WorkflowNode.InputMappingEntry",
      "map_entry": true,
      "enum_values": []
    },
    {
      "name": "output_mapping",
      "number": 6,
      "kind": "message",
      "repeated": true,
      "target": "sw4rm.workflow.WorkflowNode.OutputMappingEntry",
      "map_entry": true,
      "enum_values": []
    },
    {
      "name": "metadata",
      "number": 7,
      "kind": "message",
      "repeated": true,
      "target": "sw4rm.workflow.WorkflowNode.MetadataEntry",
      "map_entry": true,
      "enum_values": []
    }
  ],
  "sw4rm.workflow.WorkflowNode.InputMappingEntry": [
    {
      "name": "key",
      "number": 1,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "value",
      "number": 2,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.workflow.WorkflowNode.MetadataEntry": [
    {
      "name": "key",
      "number": 1,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "value",
      "number": 2,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.workflow.WorkflowNode.OutputMappingEntry": [
    {
      "name": "key",
      "number": 1,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "value",
      "number": 2,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.workflow.WorkflowState": [
    {
      "name": "workflow_id",
      "number": 1,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "node_states",
      "number": 2,
      "kind": "message",
      "repeated": true,
      "target": "sw4rm.workflow.WorkflowState.NodeStatesEntry",
      "map_entry": true,
      "enum_values": []
    },
    {
      "name": "workflow_data",
      "number": 3,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "started_at",
      "number": 4,
      "kind": "message",
      "repeated": false,
      "target": "google.protobuf.Timestamp",
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "completed_at",
      "number": 5,
      "kind": "message",
      "repeated": false,
      "target": "google.protobuf.Timestamp",
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "metadata",
      "number": 6,
      "kind": "message",
      "repeated": true,
      "target": "sw4rm.workflow.WorkflowState.MetadataEntry",
      "map_entry": true,
      "enum_values": []
    }
  ],
  "sw4rm.workflow.WorkflowState.MetadataEntry": [
    {
      "name": "key",
      "number": 1,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "value",
      "number": 2,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.workflow.WorkflowState.NodeStatesEntry": [
    {
      "name": "key",
      "number": 1,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "value",
      "number": 2,
      "kind": "message",
      "repeated": false,
      "target": "sw4rm.workflow.NodeState",
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.worktree.BindRequest": [
    {
      "name": "agent_id",
      "number": 1,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "repo_id",
      "number": 2,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "worktree_id",
      "number": 3,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.worktree.BindResponse": [
    {
      "name": "ok",
      "number": 1,
      "kind": "bool",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "reason",
      "number": 2,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.worktree.StatusRequest": [
    {
      "name": "agent_id",
      "number": 1,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.worktree.StatusResponse": [
    {
      "name": "repo_id",
      "number": 1,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "worktree_id",
      "number": 2,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "state",
      "number": 3,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.worktree.SwitchApprove": [
    {
      "name": "agent_id",
      "number": 1,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "target_worktree_id",
      "number": 2,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "ttl_ms",
      "number": 3,
      "kind": "uint64",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.worktree.SwitchReject": [
    {
      "name": "agent_id",
      "number": 1,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "reason",
      "number": 2,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.worktree.SwitchRequest": [
    {
      "name": "agent_id",
      "number": 1,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "target_worktree_id",
      "number": 2,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    },
    {
      "name": "requires_hitl",
      "number": 3,
      "kind": "bool",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.worktree.UnbindRequest": [
    {
      "name": "agent_id",
      "number": 1,
      "kind": "string",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    }
  ],
  "sw4rm.worktree.UnbindResponse": [
    {
      "name": "ok",
      "number": 1,
      "kind": "bool",
      "repeated": false,
      "target": null,
      "map_entry": false,
      "enum_values": []
    }
  ]
} as const;
