#!/usr/bin/env python3
"""Verify the committed Elixir protocol bindings stay a deliberate superset.

`sdks/ex_sdk/lib/sw4rm/proto/*.pb.ex` are generated by `mix proto.gen` from
the canonical `protos/` directory, but the committed files are a documented
superset of a fresh regeneration: the SW4-001 failure-semantics fields
(negotiation_room.pb.ex) and the SW4-002 timeout-profile messages
(common.pb.ex) are hand-maintained on top of the generated bindings until
they are promoted into canonical `protos/` (protocol decision D2).  A naive
"regenerate and diff" check would therefore always fail.

This check instead verifies the containment property that must hold:

1. Every canonical message type (and every canonical field name/number under
   it) is present in the committed Elixir bindings, so a regeneration can
   never silently drop or renumber a canonical field.
2. The documented hand-maintained SW4-001/SW4-002 extension fields are still
   present, so running proto.gen cannot silently delete them either.

Run from the repository root:  python3 scripts/check_elixir_proto_drift.py
"""
from __future__ import annotations

import re

from generate_sdk_wire_contract import ROOT, descriptors, nested_messages
from google.protobuf.descriptor import FieldDescriptor

ELIXIR_PROTO_DIR = ROOT / "sdks/ex_sdk/lib/sw4rm/proto"

# Hand-maintained extension fields that a fresh proto.gen would drop.  Keys
# are Elixir module names; values map field name -> field number.  Promoted
# to canonical protos/ under D2.
HAND_MAINTAINED_EXTENSIONS: dict = {
    # SW4-001 failure semantics: quorum bookkeeping on negotiation decisions.
    "Sw4rm.Proto.NegotiationRoom.NegotiationDecision": {
        "quorum_met": 100,
        "votes_received": 101,
        "votes_expected": 102,
        "collection_timeout_reached": 103,
        "unavailable_critics": 104,
        "late_votes": 105,
    },
    # SW4-001: per-room vote-collection timeout and quorum policy.
    "Sw4rm.Proto.NegotiationRoom.NegotiationProposal": {
        "vote_collection_timeout_s": 100,
        "quorum_policy": 101,
    },
    # SW4-002 timeout profiles (hand-maintained messages, no canonical proto).
    "Sw4rm.Proto.Common.TimeoutProfile": {
        "profile_name": 1,
        "default_timeout_ms": 2,
        "min_timeout_ms": 3,
        "max_timeout_ms": 4,
        "allow_infinite": 5,
    },
    "Sw4rm.Proto.Common.StreamingTimeoutPolicy": {
        "initial_timeout_ms": 1,
        "message_gap_timeout_ms": 2,
        "total_timeout_ms": 3,
    },
}

# A canonical message full name maps to an Elixir module by Camelizing each
# dotted segment (Macro.camelize semantics: underscore-separated words are
# each capitalized).  google.protobuf.* types ship inside the protobuf-elixir
# dependency, not in these bindings, and are therefore out of scope.
SKIP_PREFIX = "google.protobuf."

_MODULE_RE = re.compile(r"\s*defmodule\s+([\w.]+)")
_FIELD_RE = re.compile(r"\s*field\s+:([\w]+),\s*(\d+)")


def camelize(segment: str) -> str:
    return "".join(part.capitalize() for part in segment.split("_"))


def elixir_module(full_name: str) -> str | None:
    """Map a canonical message full name to its Elixir module, if bound."""
    if full_name.startswith(SKIP_PREFIX):
        return None
    # Canonical message segments are already PascalCase (proto3 message
    # names and nested message names); only the package segment is
    # snake_case and needs Camelizing.
    head, package, *rest = full_name.split(".")
    if head != "sw4rm":
        raise ValueError(f"Unexpected canonical namespace: {full_name}")
    if rest:
        return "Sw4rm.Proto." + camelize(package) + "." + ".".join(rest)
    return "Sw4rm.Proto." + camelize(package)


def parse_bindings() -> dict:
    """Return {elixir module -> {field name -> field number}} per module."""
    modules: dict = {}
    current = None
    for path in sorted(ELIXIR_PROTO_DIR.glob("*.pb.ex")):
        for line in path.read_text().splitlines():
            match = _MODULE_RE.match(line)
            if match:
                current = match.group(1)
                modules.setdefault(current, {})
                continue
            if current is None:
                continue
            field = _FIELD_RE.match(line)
            if field:
                modules[current][field.group(1)] = int(field.group(2))
    return modules


def field_pairs(message) -> list:
    """Canonical (name, number) pairs for a message's direct fields."""
    pairs: list = []
    for field in message.fields:
        if field.label == FieldDescriptor.LABEL_REPEATED and \
                field.message_type and \
                field.message_type.GetOptions().map_entry:
            continue  # map entries are inlined as map fields in the DSL
        pairs.append((field.name, field.number))
    return pairs


def check_canonical(bindings: dict, failures: list) -> int:
    """Assert every canonical message/field exists in the bindings."""
    pool, names = descriptors(ROOT)
    checked = 0
    for name in names:
        for message in pool.FindFileByName(
                name).message_types_by_name.values():
            for nested in nested_messages(message):
                if nested.GetOptions().map_entry or \
                        nested.full_name.startswith(SKIP_PREFIX):
                    continue
                module = elixir_module(nested.full_name)
                position = nested.full_name
                if bindings.get(module) is None:
                    failures.append(f"missing Elixir module {module} for "
                                    f"{position}")
                    continue
                checked += 1
                for target, number in field_pairs(nested):
                    note = f"{module}:{position}"
                    if target not in bindings[module]:
                        failures.append(f"{note} missing field {target}")
                    elif bindings[module][target] != number:
                        failures.append(f"{note} field {target} number "
                                        f"{bindings[module][target]} != "
                                        f"canonical {number}")
    return checked


def check_extensions(bindings: dict, failures: list) -> int:
    """Assert the documented hand-maintained extension fields are present."""
    checked = 0
    for module, expected in HAND_MAINTAINED_EXTENSIONS.items():
        present = bindings.get(module)
        if present is None:
            failures.append(f"hand-maintained module {module} missing")
            continue
        checked += 1
        for field, number in expected.items():
            note = f"hand-maintained field {module}.{field}"
            if present.get(field) is None:
                failures.append(f"{note} missing")
            elif present[field] != number:
                failures.append(f"{note} number {present[field]} != "
                                f"documented {number}")
    return checked


def main() -> int:
    bindings = parse_bindings()
    failures: list = []
    canonical = check_canonical(bindings, failures)
    extensions = check_extensions(bindings, failures)
    if failures:
        print(f"Elixir proto drift: {len(failures)} problem(s)")
        for failure in failures:
            print("  - " + failure)
        return 1
    print(f"Elixir proto bindings: {len(bindings)} modules, "
          f"{canonical} canonical messages verified, "
          f"{extensions} documented extension groups ok")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
