#!/usr/bin/env python3
"""Check release versions, packaged proto copies, and generated docs offline.

Mechanical consistency is separate from behavioral conformance and package
smoke tests. This command never fetches registries, installs, or publishes.
"""
from __future__ import annotations

import argparse
from dataclasses import dataclass
from functools import reduce
from pathlib import Path
import re
import subprocess
from typing import Callable

ROOT = Path(__file__).resolve().parents[1]
SEMVER = r"(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)"


@dataclass(frozen=True)
class VersionCarrier:
    path: str
    pattern: str

    def match(self, text: str) -> re.Match[str]:
        match = re.search(self.pattern, text, re.MULTILINE | re.DOTALL)
        if match is None:
            raise ValueError(f"{self.path}: missing version carrier")
        return match

    def read(self, text: str) -> str:
        return self.match(text).group("version")

    def update(self, text: str, version: str) -> str:
        match = self.match(text)
        return text[:match.start("version")] + version + text[match.end("version"):]


V = r'(?P<version>[^"\'\s]+)'
CARRIERS = (
    VersionCarrier("documentation/protocol/spec.md", rf"^Version: {V}"),
    VersionCarrier("pyproject.toml", rf'\[project\].*?^version = "{V}"'),
    VersionCarrier("sdks/py_sdk/setup.py", rf'\bversion="{V}"'),
    VersionCarrier("sdks/py_sdk/sw4rm/__init__.py", rf'^__version__ = "{V}"'),
    VersionCarrier("sdks/js_sdk/package.json", rf'\A.*?"version": "{V}"'),
    VersionCarrier("sdks/js_sdk/package-lock.json", rf'\A.*?"version": "{V}"'),
    VersionCarrier("sdks/js_sdk/package-lock.json", rf'"":\s*\{{.*?"version": "{V}"'),
    VersionCarrier("sdks/js_sdk/src/index.ts", rf"export const version = '{V}'"),
    VersionCarrier("sdks/rust_sdk/Cargo.toml", rf'\[package\].*?^version = "{V}"'),
    VersionCarrier("sdks/rust_sdk/Cargo.lock", rf'^name = "sw4rm-sdk"\nversion = "{V}"'),
    VersionCarrier("sdks/ex_sdk/mix.exs", rf'@version "{V}"'),
    VersionCarrier("sdks/cl_sdk/sw4rm-sdk.asd", rf':version "{V}"'),
)


def inventory(read: Callable[[str], str]) -> tuple[tuple[str, str], ...]:
    return tuple((carrier.path, carrier.read(read(carrier.path))) for carrier in CARRIERS)


def version_errors(rows: tuple[tuple[str, str], ...]) -> tuple[str, ...]:
    expected = rows[0][1]
    return tuple(f"{path}: expected {expected}, got {version}" for path, version in rows
                 if version != expected or re.fullmatch(SEMVER, version) is None)


def bump(root: Path, version: str) -> tuple[str, ...]:
    if re.fullmatch(SEMVER, version) is None:
        raise ValueError("Version must be SemVer X.Y.Z without leading zeroes")
    paths = tuple(dict.fromkeys(carrier.path for carrier in CARRIERS))
    # Prepare all replacements first, so a missing carrier changes no files.
    updates = tuple((path, reduce(
        lambda text, carrier: carrier.update(text, version),
        (carrier for carrier in CARRIERS if carrier.path == path),
        (root / path).read_text(),
    )) for path in paths)
    for path, text in updates:
        (root / path).write_text(text)
    return paths


@dataclass(frozen=True)
class Rpc:
    file: str
    service: str
    method: str
    request: str
    response: str


def rpc_inventory(root: Path) -> tuple[Rpc, ...]:
    def parse(path: Path) -> tuple[Rpc, ...]:
        text = re.sub(r"//[^\n]*|/\*.*?\*/", "", path.read_text(), flags=re.DOTALL)
        package = re.search(r"\bpackage\s+([\w.]+)\s*;", text).group(1)
        return tuple(
            Rpc(path.name, f"{package}.{service}", method,
                " ".join(request.split()), " ".join(response.split()))
            for service, body in re.findall(r"\bservice\s+(\w+)\s*\{(.*?)\}", text, re.DOTALL)
            for method, request, response in re.findall(
                r"\brpc\s+(\w+)\s*\(([^)]+)\)\s*returns\s*\(([^)]+)\)", body)
        )
    return tuple(rpc for path in sorted((root / "protos").glob("*.proto")) for rpc in parse(path))


def reference_document(root: Path) -> str:
    rows = inventory(lambda path: (root / path).read_text())
    # A path may be covered by more than one carrier regex; render each
    # source file once. Multiple regexes per path stay active for checking.
    deduped: dict[str, str] = {}
    for path, version in rows:
        deduped.setdefault(path, version)
    rpcs = rpc_inventory(root)
    versions = "\n".join(f"| `{path}` | {version} |" for path, version in deduped.items())
    methods = "\n".join(f"| `{r.service}` | `{r.method}` | `{r.request}` | `{r.response}` |" for r in rpcs)
    return (
        "# Source-derived release reference\n\n"
        "<!-- Generated by scripts/release_contract.py --write-docs. Do not edit. -->\n\n"
        "These are checkout versions, not proof of publication. See "
        "[release status](../release-status.md) for package availability and migration. "
        "RPC definitions describe the wire surface; they do not establish that a server "
        "implements it. See [implementation coverage](../protocol/implementation.md).\n\n"
        "## Version carriers\n\n| Source | Version |\n|---|---|\n" + versions +
        f"\n\n## RPC inventory\n\n{len(set(r.service for r in rpcs))} services, "
        f"{len(rpcs)} RPCs, {len(tuple((root / 'protos').glob('*.proto')))} proto files.\n\n"
        "| Service | RPC | Request | Response |\n|---|---|---|---|\n" + methods + "\n")


def protocol_copy_errors(root: Path) -> tuple[str, ...]:
    sources = {p.name: p.read_bytes() for p in (root / "protos").glob("*.proto")}
    copies = {p.name: p.read_bytes() for p in (root / "sdks/rust_sdk/protos").glob("*.proto")}
    return tuple(f"Rust packaged proto differs from canonical source: {name}"
                 for name in sorted(sources.keys() | copies.keys()) if sources.get(name) != copies.get(name))


def schema_document(root: Path) -> str:
    return (
        "# Canonical protobuf schema\n\n"
        "<!-- Generated by scripts/release_contract.py --write-docs. Do not edit. -->\n\n"
        "Generated from the root proto files. These define wire messages and RPCs; "
        "see [implementation coverage](../protocol/implementation.md) for running backends.\n\n"
        + "\n".join(f"## {p.name}\n\n```proto\n{p.read_text().rstrip()}\n```\n"
                    for p in sorted((root / "protos").glob("*.proto")))
    )


def base_version_errors(root: Path, base_ref: str) -> tuple[str, ...]:
    return _base_version_errors(root, base_ref, lambda path: (root / path).read_text(),
                                ["git", "diff", "--name-only", f"{base_ref}...HEAD"])


def _git_text(root: Path, ref: str, path: str) -> str:
    return subprocess.check_output(["git", "show", f"{ref}:{path}"], cwd=root, text=True)


def _index_text(root: Path, path: str) -> str:
    return subprocess.check_output(["git", "show", f":{path}"], cwd=root, text=True)


def _base_version_errors(root: Path, base_ref: str, read: Callable[[str], str],
                         changed_command: list[str]) -> tuple[str, ...]:
    previous = CARRIERS[0].read(_git_text(root, base_ref, CARRIERS[0].path))
    current = CARRIERS[0].read(read(CARRIERS[0].path))
    changed = subprocess.check_output(changed_command, cwd=root, text=True).splitlines()
    needs_bump = any(p.startswith(("protos/", "sdks/", "documentation/protocol/")) for p in changed)
    if needs_bump and tuple(map(int, current.split("."))) <= tuple(map(int, previous.split("."))):
        return (f"Protocol/SDK changed: version {current} must exceed base {previous}",)
    return ()


def resolve_base_ref(root: Path, explicit: str | None = None) -> str:
    """Resolve a stable PR-base ref; never infer a feature branch upstream."""
    configured = explicit or subprocess.run(
        ["git", "config", "--get", "release.base-ref"], cwd=root,
        text=True, capture_output=True, check=False,
    ).stdout.strip()
    if not configured:
        import os
        configured = os.environ.get("SW4RM_RELEASE_BASE_REF", "")
    candidates = [configured] if configured else []
    if not configured:
        symbolic = subprocess.run(
            ["git", "symbolic-ref", "--quiet", "refs/remotes/origin/HEAD"], cwd=root,
            text=True, capture_output=True, check=False,
        ).stdout.strip()
        if symbolic in {"refs/remotes/origin/master", "refs/remotes/origin/main"}:
            candidates.append(symbolic.removeprefix("refs/remotes/"))
        known = tuple(candidate for candidate in ("origin/master", "origin/main") if subprocess.run(
            ["git", "rev-parse", "--verify", f"{candidate}^{{commit}}"], cwd=root,
            text=True, capture_output=True, check=False,
        ).returncode == 0)
        if len(known) > 1 and not candidates:
            raise ValueError("Both origin/master and origin/main exist without origin/HEAD; "
                             "set release.base-ref or SW4RM_RELEASE_BASE_REF explicitly.")
        candidates.extend(known)
    for candidate in dict.fromkeys(candidates):
        if candidate and subprocess.run(
            ["git", "rev-parse", "--verify", f"{candidate}^{{commit}}"], cwd=root,
            text=True, capture_output=True, check=False,
        ).returncode == 0:
            return candidate
    requested = configured or "origin/HEAD, origin/master, or origin/main"
    raise ValueError(f"Unable to resolve release base '{requested}'. Set release.base-ref "
                     "or SW4RM_RELEASE_BASE_REF to a fetched origin/master or origin/main ref.")


def staged_base_version_errors(root: Path, base_ref: str | None = None) -> tuple[str, ...]:
    """Check the staged tree against a stable PR base, including cumulative changes."""
    resolved = resolve_base_ref(root, base_ref)
    merge_base = subprocess.check_output(
        ["git", "merge-base", resolved, "HEAD"], cwd=root, text=True).strip()
    return _base_version_errors(
        root, resolved, lambda path: _index_text(root, path),
        ["git", "diff", "--cached", "--name-only", merge_base],
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write-docs", action="store_true", help="Regenerate source-derived reference")
    parser.add_argument("--base-ref", help="Require a version bump relative to this local git ref")
    parser.add_argument("--staged", action="store_true", help="Check staged content against the PR base")
    args = parser.parse_args()
    if args.staged and args.write_docs:
        parser.error("--staged cannot be combined with --write-docs")
    if args.staged:
        try:
            errors = version_errors(inventory(lambda p: _index_text(ROOT, p)))
            errors += staged_base_version_errors(ROOT, args.base_ref)
        except (subprocess.CalledProcessError, ValueError) as error:
            errors = (f"Staged release check unavailable: {error}",)
    else:
        reference = ROOT / "documentation/reference/release-contract.md"
        expected = reference_document(ROOT)
        schema = ROOT / "documentation/reference/protobuf.md"
        expected_schema = schema_document(ROOT)
        if args.write_docs:
            reference.parent.mkdir(parents=True, exist_ok=True)
            reference.write_text(expected)
            schema.write_text(expected_schema)
        errors = version_errors(inventory(lambda p: (ROOT / p).read_text())) + protocol_copy_errors(ROOT)
    if not args.staged:
        if not reference.exists() or reference.read_text() != expected:
            errors += ("Generated reference stale: python scripts/release_contract.py --write-docs",)
        if not schema.exists() or schema.read_text() != expected_schema:
            errors += ("Generated schema stale: python scripts/release_contract.py --write-docs",)
    if args.base_ref and not args.staged:
        errors += base_version_errors(ROOT, args.base_ref)
    for error in errors:
        print(error)
    if not errors:
        if args.staged:
            print(f"Staged release contract OK: {len(CARRIERS)} version carriers; PR-base bump")
        else:
            print(f"Release contract OK: {len(CARRIERS)} version carriers; proto copies; generated reference")
    return int(bool(errors))


if __name__ == "__main__":
    raise SystemExit(main())
