"""Pure Rust test-source rendering for the canonical SDK wire corpus."""
from __future__ import annotations

import re
from google.protobuf.descriptor import FieldDescriptor


def snake(name: str) -> str:
    first = re.sub(r"(.)([A-Z][a-z]+)", r"\1_\2", name)
    return re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", first).lower()


def rust_type(name: str) -> str:
    if name.startswith("google.protobuf."):
        return "prost_types::" + name.rsplit(".", 1)[1]
    parts = name.split(".")
    return "sw4rm_sdk::proto::" + "::".join([*(snake(part) for part in parts[:-1]), parts[-1]])


def factory(name: str) -> str:
    return "fixture_" + "_".join(snake(part) for part in name.split("."))


def scalar(field, value: str) -> str:
    if field.type == FieldDescriptor.TYPE_MESSAGE:
        return f"{factory(field.message_type.full_name)}({value})"
    expressions = {
        FieldDescriptor.TYPE_STRING: f"({value}).as_str().unwrap().to_owned()",
        FieldDescriptor.TYPE_BYTES: f"hex::decode(({value}).as_str().unwrap()).unwrap()",
        FieldDescriptor.TYPE_INT64: f"({value}).as_str().unwrap().parse::<i64>().unwrap()",
        FieldDescriptor.TYPE_UINT64: f"({value}).as_str().unwrap().parse::<u64>().unwrap()",
        FieldDescriptor.TYPE_UINT32: f"u32::try_from(({value}).as_u64().unwrap()).unwrap()",
        FieldDescriptor.TYPE_INT32: f"i32::try_from(({value}).as_i64().unwrap()).unwrap()",
        FieldDescriptor.TYPE_ENUM: f"i32::try_from(({value}).as_i64().unwrap()).unwrap()",
        FieldDescriptor.TYPE_BOOL: f"({value}).as_bool().unwrap()",
        FieldDescriptor.TYPE_DOUBLE: f"({value}).as_f64().unwrap()",
        FieldDescriptor.TYPE_FLOAT: f"({value}).as_f64().unwrap() as f32",
    }
    if field.type not in expressions:
        raise ValueError(f"Unhandled Rust fixture field: {field.full_name}")
    return expressions[field.type]


def field_value(field) -> str:
    access = f'value["{field.name}"]'
    if field.message_type and field.message_type.GetOptions().map_entry:
        expression = scalar(field.message_type.fields_by_name["value"], "item")
        return f'({access}).as_object().unwrap().iter().map(|(key, item)| (key.clone(), {expression})).collect()'
    if field.label == FieldDescriptor.LABEL_REPEATED:
        return f'({access}).as_array().unwrap().iter().map(|item| {scalar(field, "item")}).collect()'
    expression = scalar(field, f"&{access}" if field.message_type else access)
    return f"Some({expression})" if field.message_type else expression


def render_factories(messages) -> str:
    def render(message):
        name = rust_type(message.full_name)
        fields = "\n".join(f'        r#{field.name}: if value.get("{field.name}").is_some() {{ {field_value(field)} }} else {{ Default::default() }},'
                           for field in message.fields)
        argument = "value" if message.fields else "_value"
        return f"fn {factory(message.full_name)}({argument}: &serde_json::Value) -> {name} {{\n    {name} {{\n{fields}\n    }}\n}}\n"
    return "\n".join(render(message) for message in messages)


def render_rpc(rpc) -> str:
    _, service, method = rpc.path.split("/")
    package, service_name = service.rsplit(".", 1)
    client = "sw4rm_sdk::proto::" + package.replace(".", "::") + "::" + snake(service_name) + "_client::" + service_name + "Client"
    response = rust_type(rpc.response)
    if rpc.server_streaming:
        verify = f'''for expected_variant in ["sample", "edge"] {{
                    let expected = fixture::<{response}>(&vectors, "{rpc.response}", expected_variant);
                    assert_eq!(result.message().await.unwrap().unwrap(), expected, "{rpc.path}");
                }}
                assert!(result.message().await.unwrap().is_none());'''
    else:
        verify = f'assert_eq!(result, fixture::<{response}>(&vectors, "{rpc.response}", variant), "{rpc.path}");'
    mutable = "mut " if rpc.server_streaming else ""
    return f'''    {{
        let mut client = {client}::new(channel.clone());
        for variant in ["sample", "edge"] {{
            let mut request = tonic::Request::new(fixture::<{rust_type(rpc.request)}>(&vectors, "{rpc.request}", variant));
            request.metadata_mut().insert("sw4rm-vector", variant.parse().unwrap());
            request.set_timeout(std::time::Duration::from_secs(3));
            let {mutable}result = client.{snake(method)}(request).await.unwrap().into_inner();
            {verify}
        }}
    }}'''


def render(messages, rpcs, variants: int = 4) -> str:
    messages = tuple(message for message in messages if not message.GetOptions().map_entry)
    dispatch = "\n".join(f'            "{message.full_name}" => check(vector, {factory(message.full_name)}(&vector["value"])), '
                         for message in messages)
    return '''// Generated by scripts/generate_sdk_wire_contract.py --write.
// Expected structs come from fixture values; wire bytes come from Python protobuf.
use prost::Message;
use serde_json::Value;

fn vectors() -> Vec<Value> {
    let gz = include_bytes!("../../../tests/conformance_vectors/wire_vectors.json.gz");
    let mut decoder = flate2::read::GzDecoder::new(&gz[..]);
    serde_json::from_reader::<_, Value>(decoder)
        .unwrap()["vectors"].as_array().unwrap().clone()
}

fn check<M: Message + Default + PartialEq + std::fmt::Debug>(vector: &Value, expected: M) {
    let wire = hex::decode(vector["wire_hex"].as_str().unwrap()).unwrap();
    let actual = M::decode(wire.as_slice()).unwrap();
    assert_eq!(actual, expected, "{}", vector["id"]);
    assert_eq!(M::decode(expected.encode_to_vec().as_slice()).unwrap(), expected);
    // Byte canonicality (R24): map fields use BTreeMap codegen, so sorted-key
    // re-encoding must reproduce the recorded corpus bytes exactly. prost
    // applies proto3 default-omission, so an explicit -0.0 (== 0.0) is
    // dropped while Python protobuf writes it; like the Elixir suite, vectors
    // whose re-encode stays length-stable are pinned byte-exact and the rest
    // stay pinned semantically.
    let reencoded = expected.encode_to_vec();
    if reencoded.len() == wire.len() {
        assert_eq!(reencoded, wire, "{}", vector["id"]);
    }
}

#[test]
fn canonical_message_vectors() {
    let vectors = vectors();
    assert_eq!(vectors.len(), ''' + str(len(messages) * variants) + ''');
    for vector in &vectors {
        match vector["type"].as_str().unwrap() {
''' + dispatch + '''
            unknown => panic!("unhandled canonical message {unknown}"),
        }
    }
}

fn fixture<M: Message + Default>(vectors: &[Value], name: &str, variant: &str) -> M {
    let id = format!("{name}:{variant}");
    let vector = vectors.iter().find(|v| v["id"] == id).unwrap();
    M::decode(hex::decode(vector["wire_hex"].as_str().unwrap()).unwrap().as_slice()).unwrap()
}

struct Server(std::process::Child);
impl Drop for Server {
    fn drop(&mut self) { let _ = self.0.kill(); let _ = self.0.wait(); }
}

#[tokio::test]
#[ignore = "requires SW4RM_TEST_PYTHON with the existing Python gRPC dependencies"]
async fn canonical_rpcs_against_python() {
    use std::io::{BufRead, BufReader};
    use std::process::{Command, Stdio};
    let root = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../..");
    let python = std::env::var("SW4RM_TEST_PYTHON").expect("set SW4RM_TEST_PYTHON");
    let mut server = Server(Command::new(python)
        .arg(root.join("tests/sdk_parity/wire_contract_server.py"))
        .env("PYTHONPATH", root.join("sdks/py_sdk"))
        .stdout(Stdio::piped()).stderr(Stdio::inherit()).spawn().unwrap());
    let stdout = server.0.stdout.take().unwrap();
    let (send, receive) = std::sync::mpsc::channel();
    std::thread::spawn(move || {
        let mut line = String::new();
        let result = BufReader::new(stdout).read_line(&mut line).map(|_| line);
        let _ = send.send(result);
    });
    let line = receive.recv_timeout(std::time::Duration::from_secs(10)).unwrap().unwrap();
    let ready: Value = serde_json::from_str(&line).unwrap();
    let channel = tonic::transport::Endpoint::from_shared(format!("http://127.0.0.1:{}", ready["port"]))
        .unwrap().connect_timeout(std::time::Duration::from_secs(3)).connect().await.unwrap();
    let vectors = vectors();
''' + "\n".join(render_rpc(rpc) for rpc in rpcs) + "\n}\n\n" + render_factories(messages)
