# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: connector.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x63onnector.proto\x12\x11\x61gentos.connector\"\xc6\x01\n\x0eToolDescriptor\x12\x11\n\ttool_name\x18\x01 \x01(\t\x12\x14\n\x0cinput_schema\x18\x02 \x01(\t\x12\x15\n\routput_schema\x18\x03 \x01(\t\x12\x12\n\nidempotent\x18\x04 \x01(\x08\x12\x16\n\x0eneeds_worktree\x18\x05 \x01(\x08\x12\x19\n\x11\x64\x65\x66\x61ult_timeout_s\x18\x06 \x01(\r\x12\x17\n\x0fmax_concurrency\x18\x07 \x01(\r\x12\x14\n\x0cside_effects\x18\x08 \x01(\t\"`\n\x17ProviderRegisterRequest\x12\x13\n\x0bprovider_id\x18\x01 \x01(\t\x12\x30\n\x05tools\x18\x02 \x03(\x0b\x32!.agentos.connector.ToolDescriptor\"6\n\x18ProviderRegisterResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0e\n\x06reason\x18\x02 \x01(\t\"+\n\x14\x44\x65scribeToolsRequest\x12\x13\n\x0bprovider_id\x18\x01 \x01(\t\"I\n\x15\x44\x65scribeToolsResponse\x12\x30\n\x05tools\x18\x01 \x03(\x0b\x32!.agentos.connector.ToolDescriptor2\xe3\x01\n\x10\x43onnectorService\x12k\n\x10RegisterProvider\x12*.agentos.connector.ProviderRegisterRequest\x1a+.agentos.connector.ProviderRegisterResponse\x12\x62\n\rDescribeTools\x12\'.agentos.connector.DescribeToolsRequest\x1a(.agentos.connector.DescribeToolsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'connector_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TOOLDESCRIPTOR']._serialized_start=39
  _globals['_TOOLDESCRIPTOR']._serialized_end=237
  _globals['_PROVIDERREGISTERREQUEST']._serialized_start=239
  _globals['_PROVIDERREGISTERREQUEST']._serialized_end=335
  _globals['_PROVIDERREGISTERRESPONSE']._serialized_start=337
  _globals['_PROVIDERREGISTERRESPONSE']._serialized_end=391
  _globals['_DESCRIBETOOLSREQUEST']._serialized_start=393
  _globals['_DESCRIBETOOLSREQUEST']._serialized_end=436
  _globals['_DESCRIBETOOLSRESPONSE']._serialized_start=438
  _globals['_DESCRIBETOOLSRESPONSE']._serialized_end=511
  _globals['_CONNECTORSERVICE']._serialized_start=514
  _globals['_CONNECTORSERVICE']._serialized_end=741
# @@protoc_insertion_point(module_scope)
