# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import connector_pb2 as connector__pb2


class ConnectorServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterProvider = channel.unary_unary(
                '/agentos.connector.ConnectorService/RegisterProvider',
                request_serializer=connector__pb2.ProviderRegisterRequest.SerializeToString,
                response_deserializer=connector__pb2.ProviderRegisterResponse.FromString,
                )
        self.DescribeTools = channel.unary_unary(
                '/agentos.connector.ConnectorService/DescribeTools',
                request_serializer=connector__pb2.DescribeToolsRequest.SerializeToString,
                response_deserializer=connector__pb2.DescribeToolsResponse.FromString,
                )


class ConnectorServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterProvider(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DescribeTools(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ConnectorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterProvider': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterProvider,
                    request_deserializer=connector__pb2.ProviderRegisterRequest.FromString,
                    response_serializer=connector__pb2.ProviderRegisterResponse.SerializeToString,
            ),
            'DescribeTools': grpc.unary_unary_rpc_method_handler(
                    servicer.DescribeTools,
                    request_deserializer=connector__pb2.DescribeToolsRequest.FromString,
                    response_serializer=connector__pb2.DescribeToolsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agentos.connector.ConnectorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ConnectorService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterProvider(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/agentos.connector.ConnectorService/RegisterProvider',
            connector__pb2.ProviderRegisterRequest.SerializeToString,
            connector__pb2.ProviderRegisterResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DescribeTools(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/agentos.connector.ConnectorService/DescribeTools',
            connector__pb2.DescribeToolsRequest.SerializeToString,
            connector__pb2.DescribeToolsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
