# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hitl.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nhitl.proto\x12\x0c\x61gentos.hitl\x1a\x0c\x63ommon.proto\"\x82\x01\n\x0eHitlInvocation\x12\x33\n\x0breason_type\x18\x01 \x01(\x0e\x32\x1e.agentos.common.HitlReasonType\x12\x0f\n\x07\x63ontext\x18\x02 \x01(\x0c\x12\x18\n\x10proposed_actions\x18\x03 \x03(\t\x12\x10\n\x08priority\x18\x04 \x01(\x05\"K\n\x0cHitlDecision\x12\x0e\n\x06\x61\x63tion\x18\x01 \x01(\t\x12\x18\n\x10\x64\x65\x63ision_payload\x18\x02 \x01(\x0c\x12\x11\n\trationale\x18\x03 \x01(\t2Q\n\x0bHitlService\x12\x42\n\x06\x44\x65\x63ide\x12\x1c.agentos.hitl.HitlInvocation\x1a\x1a.agentos.hitl.HitlDecisionb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hitl_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_HITLINVOCATION']._serialized_start=43
  _globals['_HITLINVOCATION']._serialized_end=173
  _globals['_HITLDECISION']._serialized_start=175
  _globals['_HITLDECISION']._serialized_end=250
  _globals['_HITLSERVICE']._serialized_start=252
  _globals['_HITLSERVICE']._serialized_end=333
# @@protoc_insertion_point(module_scope)
