# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: logging.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rlogging.proto\x12\x0f\x61gentos.logging\x1a\x1fgoogle/protobuf/timestamp.proto\"\x95\x01\n\x08LogEvent\x12&\n\x02ts\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x16\n\x0e\x63orrelation_id\x18\x02 \x01(\t\x12\x10\n\x08\x61gent_id\x18\x03 \x01(\t\x12\x12\n\nevent_type\x18\x04 \x01(\t\x12\r\n\x05level\x18\x05 \x01(\t\x12\x14\n\x0c\x64\x65tails_json\x18\x06 \x01(\t\"\x1c\n\x0eIngestResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x32V\n\x0eLoggingService\x12\x44\n\x06Ingest\x12\x19.agentos.logging.LogEvent\x1a\x1f.agentos.logging.IngestResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'logging_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_LOGEVENT']._serialized_start=68
  _globals['_LOGEVENT']._serialized_end=217
  _globals['_INGESTRESPONSE']._serialized_start=219
  _globals['_INGESTRESPONSE']._serialized_end=247
  _globals['_LOGGINGSERVICE']._serialized_start=249
  _globals['_LOGGINGSERVICE']._serialized_end=335
# @@protoc_insertion_point(module_scope)
