# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import common_pb2 as common__pb2
import negotiation_pb2 as negotiation__pb2


class NegotiationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Open = channel.unary_unary(
                '/agentos.negotiation.NegotiationService/Open',
                request_serializer=negotiation__pb2.NegotiationOpen.SerializeToString,
                response_deserializer=common__pb2.Empty.FromString,
                )
        self.Propose = channel.unary_unary(
                '/agentos.negotiation.NegotiationService/Propose',
                request_serializer=negotiation__pb2.Proposal.SerializeToString,
                response_deserializer=common__pb2.Empty.FromString,
                )
        self.Counter = channel.unary_unary(
                '/agentos.negotiation.NegotiationService/Counter',
                request_serializer=negotiation__pb2.CounterProposal.SerializeToString,
                response_deserializer=common__pb2.Empty.FromString,
                )
        self.Evaluate = channel.unary_unary(
                '/agentos.negotiation.NegotiationService/Evaluate',
                request_serializer=negotiation__pb2.Evaluation.SerializeToString,
                response_deserializer=common__pb2.Empty.FromString,
                )
        self.Decide = channel.unary_unary(
                '/agentos.negotiation.NegotiationService/Decide',
                request_serializer=negotiation__pb2.Decision.SerializeToString,
                response_deserializer=common__pb2.Empty.FromString,
                )
        self.Abort = channel.unary_unary(
                '/agentos.negotiation.NegotiationService/Abort',
                request_serializer=negotiation__pb2.AbortRequest.SerializeToString,
                response_deserializer=common__pb2.Empty.FromString,
                )


class NegotiationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Open(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Propose(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Counter(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Evaluate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Decide(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Abort(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NegotiationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Open': grpc.unary_unary_rpc_method_handler(
                    servicer.Open,
                    request_deserializer=negotiation__pb2.NegotiationOpen.FromString,
                    response_serializer=common__pb2.Empty.SerializeToString,
            ),
            'Propose': grpc.unary_unary_rpc_method_handler(
                    servicer.Propose,
                    request_deserializer=negotiation__pb2.Proposal.FromString,
                    response_serializer=common__pb2.Empty.SerializeToString,
            ),
            'Counter': grpc.unary_unary_rpc_method_handler(
                    servicer.Counter,
                    request_deserializer=negotiation__pb2.CounterProposal.FromString,
                    response_serializer=common__pb2.Empty.SerializeToString,
            ),
            'Evaluate': grpc.unary_unary_rpc_method_handler(
                    servicer.Evaluate,
                    request_deserializer=negotiation__pb2.Evaluation.FromString,
                    response_serializer=common__pb2.Empty.SerializeToString,
            ),
            'Decide': grpc.unary_unary_rpc_method_handler(
                    servicer.Decide,
                    request_deserializer=negotiation__pb2.Decision.FromString,
                    response_serializer=common__pb2.Empty.SerializeToString,
            ),
            'Abort': grpc.unary_unary_rpc_method_handler(
                    servicer.Abort,
                    request_deserializer=negotiation__pb2.AbortRequest.FromString,
                    response_serializer=common__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agentos.negotiation.NegotiationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class NegotiationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Open(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/agentos.negotiation.NegotiationService/Open',
            negotiation__pb2.NegotiationOpen.SerializeToString,
            common__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Propose(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/agentos.negotiation.NegotiationService/Propose',
            negotiation__pb2.Proposal.SerializeToString,
            common__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Counter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/agentos.negotiation.NegotiationService/Counter',
            negotiation__pb2.CounterProposal.SerializeToString,
            common__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Evaluate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/agentos.negotiation.NegotiationService/Evaluate',
            negotiation__pb2.Evaluation.SerializeToString,
            common__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Decide(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/agentos.negotiation.NegotiationService/Decide',
            negotiation__pb2.Decision.SerializeToString,
            common__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Abort(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/agentos.negotiation.NegotiationService/Abort',
            negotiation__pb2.AbortRequest.SerializeToString,
            common__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
