# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: negotiation.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2
from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11negotiation.proto\x12\x13\x61gentos.negotiation\x1a\x0c\x63ommon.proto\x1a\x1egoogle/protobuf/duration.proto\"\xcd\x01\n\x0fNegotiationOpen\x12\x16\n\x0enegotiation_id\x18\x01 \x01(\t\x12\x16\n\x0e\x63orrelation_id\x18\x02 \x01(\t\x12\r\n\x05topic\x18\x03 \x01(\t\x12\x14\n\x0cparticipants\x18\x04 \x03(\t\x12\x32\n\tintensity\x18\x05 \x01(\x0e\x32\x1f.agentos.common.DebateIntensity\x12\x31\n\x0e\x64\x65\x62\x61te_timeout\x18\x06 \x01(\x0b\x32\x19.google.protobuf.Duration\"]\n\x08Proposal\x12\x16\n\x0enegotiation_id\x18\x01 \x01(\t\x12\x12\n\nfrom_agent\x18\x02 \x01(\t\x12\x14\n\x0c\x63ontent_type\x18\x03 \x01(\t\x12\x0f\n\x07payload\x18\x04 \x01(\x0c\"d\n\x0f\x43ounterProposal\x12\x16\n\x0enegotiation_id\x18\x01 \x01(\t\x12\x12\n\nfrom_agent\x18\x02 \x01(\t\x12\x14\n\x0c\x63ontent_type\x18\x03 \x01(\t\x12\x0f\n\x07payload\x18\x04 \x01(\x0c\"a\n\nEvaluation\x12\x16\n\x0enegotiation_id\x18\x01 \x01(\t\x12\x12\n\nfrom_agent\x18\x02 \x01(\t\x12\x18\n\x10\x63onfidence_score\x18\x03 \x01(\x01\x12\r\n\x05notes\x18\x04 \x01(\t\"\\\n\x08\x44\x65\x63ision\x12\x16\n\x0enegotiation_id\x18\x01 \x01(\t\x12\x12\n\ndecided_by\x18\x02 \x01(\t\x12\x14\n\x0c\x63ontent_type\x18\x03 \x01(\t\x12\x0e\n\x06result\x18\x04 \x01(\x0c\"6\n\x0c\x41\x62ortRequest\x12\x16\n\x0enegotiation_id\x18\x01 \x01(\t\x12\x0e\n\x06reason\x18\x02 \x01(\t2\xa9\x03\n\x12NegotiationService\x12\x43\n\x04Open\x12$.agentos.negotiation.NegotiationOpen\x1a\x15.agentos.common.Empty\x12?\n\x07Propose\x12\x1d.agentos.negotiation.Proposal\x1a\x15.agentos.common.Empty\x12\x46\n\x07\x43ounter\x12$.agentos.negotiation.CounterProposal\x1a\x15.agentos.common.Empty\x12\x42\n\x08\x45valuate\x12\x1f.agentos.negotiation.Evaluation\x1a\x15.agentos.common.Empty\x12>\n\x06\x44\x65\x63ide\x12\x1d.agentos.negotiation.Decision\x1a\x15.agentos.common.Empty\x12\x41\n\x05\x41\x62ort\x12!.agentos.negotiation.AbortRequest\x1a\x15.agentos.common.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'negotiation_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_NEGOTIATIONOPEN']._serialized_start=89
  _globals['_NEGOTIATIONOPEN']._serialized_end=294
  _globals['_PROPOSAL']._serialized_start=296
  _globals['_PROPOSAL']._serialized_end=389
  _globals['_COUNTERPROPOSAL']._serialized_start=391
  _globals['_COUNTERPROPOSAL']._serialized_end=491
  _globals['_EVALUATION']._serialized_start=493
  _globals['_EVALUATION']._serialized_end=590
  _globals['_DECISION']._serialized_start=592
  _globals['_DECISION']._serialized_end=684
  _globals['_ABORTREQUEST']._serialized_start=686
  _globals['_ABORTREQUEST']._serialized_end=740
  _globals['_NEGOTIATIONSERVICE']._serialized_start=743
  _globals['_NEGOTIATIONSERVICE']._serialized_end=1168
# @@protoc_insertion_point(module_scope)
