# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import reasoning_pb2 as reasoning__pb2


class ReasoningProxyStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CheckParallelism = channel.unary_unary(
                '/agentos.reasoning.ReasoningProxy/CheckParallelism',
                request_serializer=reasoning__pb2.ParallelismCheckRequest.SerializeToString,
                response_deserializer=reasoning__pb2.ParallelismCheckResponse.FromString,
                )
        self.EvaluateDebate = channel.unary_unary(
                '/agentos.reasoning.ReasoningProxy/EvaluateDebate',
                request_serializer=reasoning__pb2.DebateEvaluateRequest.SerializeToString,
                response_deserializer=reasoning__pb2.DebateEvaluateResponse.FromString,
                )


class ReasoningProxyServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CheckParallelism(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EvaluateDebate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReasoningProxyServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CheckParallelism': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckParallelism,
                    request_deserializer=reasoning__pb2.ParallelismCheckRequest.FromString,
                    response_serializer=reasoning__pb2.ParallelismCheckResponse.SerializeToString,
            ),
            'EvaluateDebate': grpc.unary_unary_rpc_method_handler(
                    servicer.EvaluateDebate,
                    request_deserializer=reasoning__pb2.DebateEvaluateRequest.FromString,
                    response_serializer=reasoning__pb2.DebateEvaluateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agentos.reasoning.ReasoningProxy', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ReasoningProxy(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CheckParallelism(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/agentos.reasoning.ReasoningProxy/CheckParallelism',
            reasoning__pb2.ParallelismCheckRequest.SerializeToString,
            reasoning__pb2.ParallelismCheckResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def EvaluateDebate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/agentos.reasoning.ReasoningProxy/EvaluateDebate',
            reasoning__pb2.DebateEvaluateRequest.SerializeToString,
            reasoning__pb2.DebateEvaluateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
