# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: reasoning.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0freasoning.proto\x12\x11\x61gentos.reasoning\";\n\x17ParallelismCheckRequest\x12\x0f\n\x07scope_a\x18\x01 \x01(\t\x12\x0f\n\x07scope_b\x18\x02 \x01(\t\"C\n\x18ParallelismCheckResponse\x12\x18\n\x10\x63onfidence_score\x18\x01 \x01(\x01\x12\r\n\x05notes\x18\x02 \x01(\t\"j\n\x15\x44\x65\x62\x61teEvaluateRequest\x12\x16\n\x0enegotiation_id\x18\x01 \x01(\t\x12\x12\n\nproposal_a\x18\x02 \x01(\t\x12\x12\n\nproposal_b\x18\x03 \x01(\t\x12\x11\n\tintensity\x18\x04 \x01(\t\"A\n\x16\x44\x65\x62\x61teEvaluateResponse\x12\x18\n\x10\x63onfidence_score\x18\x01 \x01(\x01\x12\r\n\x05notes\x18\x02 \x01(\t2\xe4\x01\n\x0eReasoningProxy\x12k\n\x10\x43heckParallelism\x12*.agentos.reasoning.ParallelismCheckRequest\x1a+.agentos.reasoning.ParallelismCheckResponse\x12\x65\n\x0e\x45valuateDebate\x12(.agentos.reasoning.DebateEvaluateRequest\x1a).agentos.reasoning.DebateEvaluateResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'reasoning_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PARALLELISMCHECKREQUEST']._serialized_start=38
  _globals['_PARALLELISMCHECKREQUEST']._serialized_end=97
  _globals['_PARALLELISMCHECKRESPONSE']._serialized_start=99
  _globals['_PARALLELISMCHECKRESPONSE']._serialized_end=166
  _globals['_DEBATEEVALUATEREQUEST']._serialized_start=168
  _globals['_DEBATEEVALUATEREQUEST']._serialized_end=274
  _globals['_DEBATEEVALUATERESPONSE']._serialized_start=276
  _globals['_DEBATEEVALUATERESPONSE']._serialized_end=341
  _globals['_REASONINGPROXY']._serialized_start=344
  _globals['_REASONINGPROXY']._serialized_end=572
# @@protoc_insertion_point(module_scope)
