# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import registry_pb2 as registry__pb2


class RegistryServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterAgent = channel.unary_unary(
                '/agentos.registry.RegistryService/RegisterAgent',
                request_serializer=registry__pb2.RegisterAgentRequest.SerializeToString,
                response_deserializer=registry__pb2.RegisterAgentResponse.FromString,
                )
        self.Heartbeat = channel.unary_unary(
                '/agentos.registry.RegistryService/Heartbeat',
                request_serializer=registry__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=registry__pb2.HeartbeatResponse.FromString,
                )
        self.DeregisterAgent = channel.unary_unary(
                '/agentos.registry.RegistryService/DeregisterAgent',
                request_serializer=registry__pb2.DeregisterAgentRequest.SerializeToString,
                response_deserializer=registry__pb2.DeregisterAgentResponse.FromString,
                )


class RegistryServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterAgent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeregisterAgent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RegistryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterAgent,
                    request_deserializer=registry__pb2.RegisterAgentRequest.FromString,
                    response_serializer=registry__pb2.RegisterAgentResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=registry__pb2.HeartbeatRequest.FromString,
                    response_serializer=registry__pb2.HeartbeatResponse.SerializeToString,
            ),
            'DeregisterAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.DeregisterAgent,
                    request_deserializer=registry__pb2.DeregisterAgentRequest.FromString,
                    response_serializer=registry__pb2.DeregisterAgentResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agentos.registry.RegistryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RegistryService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/agentos.registry.RegistryService/RegisterAgent',
            registry__pb2.RegisterAgentRequest.SerializeToString,
            registry__pb2.RegisterAgentResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/agentos.registry.RegistryService/Heartbeat',
            registry__pb2.HeartbeatRequest.SerializeToString,
            registry__pb2.HeartbeatResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeregisterAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/agentos.registry.RegistryService/DeregisterAgent',
            registry__pb2.DeregisterAgentRequest.SerializeToString,
            registry__pb2.DeregisterAgentResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
