# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: registry.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eregistry.proto\x12\x10\x61gentos.registry\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x0c\x63ommon.proto\"\xed\x01\n\x0f\x41gentDescriptor\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x14\n\x0c\x63\x61pabilities\x18\x04 \x03(\t\x12?\n\x13\x63ommunication_class\x18\x05 \x01(\x0e\x32\".agentos.common.CommunicationClass\x12\x1c\n\x14modalities_supported\x18\x06 \x03(\t\x12\x1c\n\x14reasoning_connectors\x18\x07 \x03(\t\x12\x12\n\npublic_key\x18\x08 \x01(\x0c\"H\n\x14RegisterAgentRequest\x12\x30\n\x05\x61gent\x18\x01 \x01(\x0b\x32!.agentos.registry.AgentDescriptor\"9\n\x15RegisterAgentResponse\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\x08\x12\x0e\n\x06reason\x18\x02 \x01(\t\"\xbe\x01\n\x10HeartbeatRequest\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\x12)\n\x05state\x18\x02 \x01(\x0e\x32\x1a.agentos.common.AgentState\x12>\n\x06health\x18\x03 \x03(\x0b\x32..agentos.registry.HeartbeatRequest.HealthEntry\x1a-\n\x0bHealthEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x1f\n\x11HeartbeatResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\":\n\x16\x44\x65registerAgentRequest\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\x12\x0e\n\x06reason\x18\x02 \x01(\t\"%\n\x17\x44\x65registerAgentResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x32\xb1\x02\n\x0fRegistryService\x12`\n\rRegisterAgent\x12&.agentos.registry.RegisterAgentRequest\x1a\'.agentos.registry.RegisterAgentResponse\x12T\n\tHeartbeat\x12\".agentos.registry.HeartbeatRequest\x1a#.agentos.registry.HeartbeatResponse\x12\x66\n\x0f\x44\x65registerAgent\x12(.agentos.registry.DeregisterAgentRequest\x1a).agentos.registry.DeregisterAgentResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'registry_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_HEARTBEATREQUEST_HEALTHENTRY']._options = None
  _globals['_HEARTBEATREQUEST_HEALTHENTRY']._serialized_options = b'8\001'
  _globals['_AGENTDESCRIPTOR']._serialized_start=84
  _globals['_AGENTDESCRIPTOR']._serialized_end=321
  _globals['_REGISTERAGENTREQUEST']._serialized_start=323
  _globals['_REGISTERAGENTREQUEST']._serialized_end=395
  _globals['_REGISTERAGENTRESPONSE']._serialized_start=397
  _globals['_REGISTERAGENTRESPONSE']._serialized_end=454
  _globals['_HEARTBEATREQUEST']._serialized_start=457
  _globals['_HEARTBEATREQUEST']._serialized_end=647
  _globals['_HEARTBEATREQUEST_HEALTHENTRY']._serialized_start=602
  _globals['_HEARTBEATREQUEST_HEALTHENTRY']._serialized_end=647
  _globals['_HEARTBEATRESPONSE']._serialized_start=649
  _globals['_HEARTBEATRESPONSE']._serialized_end=680
  _globals['_DEREGISTERAGENTREQUEST']._serialized_start=682
  _globals['_DEREGISTERAGENTREQUEST']._serialized_end=740
  _globals['_DEREGISTERAGENTRESPONSE']._serialized_start=742
  _globals['_DEREGISTERAGENTRESPONSE']._serialized_end=779
  _globals['_REGISTRYSERVICE']._serialized_start=782
  _globals['_REGISTRYSERVICE']._serialized_end=1087
# @@protoc_insertion_point(module_scope)
