# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import router_pb2 as router__pb2


class RouterServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendMessage = channel.unary_unary(
                '/agentos.router.RouterService/SendMessage',
                request_serializer=router__pb2.SendMessageRequest.SerializeToString,
                response_deserializer=router__pb2.SendMessageResponse.FromString,
                )
        self.StreamIncoming = channel.unary_stream(
                '/agentos.router.RouterService/StreamIncoming',
                request_serializer=router__pb2.StreamRequest.SerializeToString,
                response_deserializer=router__pb2.StreamItem.FromString,
                )


class RouterServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamIncoming(self, request, context):
        """per-agent inbound stream
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RouterServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.SendMessage,
                    request_deserializer=router__pb2.SendMessageRequest.FromString,
                    response_serializer=router__pb2.SendMessageResponse.SerializeToString,
            ),
            'StreamIncoming': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamIncoming,
                    request_deserializer=router__pb2.StreamRequest.FromString,
                    response_serializer=router__pb2.StreamItem.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agentos.router.RouterService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RouterService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/agentos.router.RouterService/SendMessage',
            router__pb2.SendMessageRequest.SerializeToString,
            router__pb2.SendMessageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StreamIncoming(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/agentos.router.RouterService/StreamIncoming',
            router__pb2.StreamRequest.SerializeToString,
            router__pb2.StreamItem.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
