# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: router.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0crouter.proto\x12\x0e\x61gentos.router\x1a\x0c\x63ommon.proto\";\n\x12SendMessageRequest\x12%\n\x03msg\x18\x01 \x01(\x0b\x32\x18.agentos.common.Envelope\"7\n\x13SendMessageResponse\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\x08\x12\x0e\n\x06reason\x18\x02 \x01(\t\"!\n\rStreamRequest\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\"3\n\nStreamItem\x12%\n\x03msg\x18\x01 \x01(\x0b\x32\x18.agentos.common.Envelope2\xb6\x01\n\rRouterService\x12V\n\x0bSendMessage\x12\".agentos.router.SendMessageRequest\x1a#.agentos.router.SendMessageResponse\x12M\n\x0eStreamIncoming\x12\x1d.agentos.router.StreamRequest\x1a\x1a.agentos.router.StreamItem0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'router_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SENDMESSAGEREQUEST']._serialized_start=46
  _globals['_SENDMESSAGEREQUEST']._serialized_end=105
  _globals['_SENDMESSAGERESPONSE']._serialized_start=107
  _globals['_SENDMESSAGERESPONSE']._serialized_end=162
  _globals['_STREAMREQUEST']._serialized_start=164
  _globals['_STREAMREQUEST']._serialized_end=197
  _globals['_STREAMITEM']._serialized_start=199
  _globals['_STREAMITEM']._serialized_end=250
  _globals['_ROUTERSERVICE']._serialized_start=253
  _globals['_ROUTERSERVICE']._serialized_end=435
# @@protoc_insertion_point(module_scope)
