# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import scheduler_pb2 as scheduler__pb2


class SchedulerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitTask = channel.unary_unary(
                '/agentos.scheduler.SchedulerService/SubmitTask',
                request_serializer=scheduler__pb2.SubmitTaskRequest.SerializeToString,
                response_deserializer=scheduler__pb2.SubmitTaskResponse.FromString,
                )
        self.RequestPreemption = channel.unary_unary(
                '/agentos.scheduler.SchedulerService/RequestPreemption',
                request_serializer=scheduler__pb2.PreemptRequest.SerializeToString,
                response_deserializer=scheduler__pb2.PreemptResponse.FromString,
                )
        self.ShutdownAgent = channel.unary_unary(
                '/agentos.scheduler.SchedulerService/ShutdownAgent',
                request_serializer=scheduler__pb2.ShutdownAgentRequest.SerializeToString,
                response_deserializer=scheduler__pb2.ShutdownAgentResponse.FromString,
                )
        self.PollActivityBuffer = channel.unary_unary(
                '/agentos.scheduler.SchedulerService/PollActivityBuffer',
                request_serializer=scheduler__pb2.PollActivityBufferRequest.SerializeToString,
                response_deserializer=scheduler__pb2.PollActivityBufferResponse.FromString,
                )
        self.PurgeActivity = channel.unary_unary(
                '/agentos.scheduler.SchedulerService/PurgeActivity',
                request_serializer=scheduler__pb2.PurgeActivityRequest.SerializeToString,
                response_deserializer=scheduler__pb2.PurgeActivityResponse.FromString,
                )


class SchedulerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SubmitTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestPreemption(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ShutdownAgent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PollActivityBuffer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PurgeActivity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SchedulerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitTask': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitTask,
                    request_deserializer=scheduler__pb2.SubmitTaskRequest.FromString,
                    response_serializer=scheduler__pb2.SubmitTaskResponse.SerializeToString,
            ),
            'RequestPreemption': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestPreemption,
                    request_deserializer=scheduler__pb2.PreemptRequest.FromString,
                    response_serializer=scheduler__pb2.PreemptResponse.SerializeToString,
            ),
            'ShutdownAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.ShutdownAgent,
                    request_deserializer=scheduler__pb2.ShutdownAgentRequest.FromString,
                    response_serializer=scheduler__pb2.ShutdownAgentResponse.SerializeToString,
            ),
            'PollActivityBuffer': grpc.unary_unary_rpc_method_handler(
                    servicer.PollActivityBuffer,
                    request_deserializer=scheduler__pb2.PollActivityBufferRequest.FromString,
                    response_serializer=scheduler__pb2.PollActivityBufferResponse.SerializeToString,
            ),
            'PurgeActivity': grpc.unary_unary_rpc_method_handler(
                    servicer.PurgeActivity,
                    request_deserializer=scheduler__pb2.PurgeActivityRequest.FromString,
                    response_serializer=scheduler__pb2.PurgeActivityResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agentos.scheduler.SchedulerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SchedulerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SubmitTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/agentos.scheduler.SchedulerService/SubmitTask',
            scheduler__pb2.SubmitTaskRequest.SerializeToString,
            scheduler__pb2.SubmitTaskResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RequestPreemption(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/agentos.scheduler.SchedulerService/RequestPreemption',
            scheduler__pb2.PreemptRequest.SerializeToString,
            scheduler__pb2.PreemptResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ShutdownAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/agentos.scheduler.SchedulerService/ShutdownAgent',
            scheduler__pb2.ShutdownAgentRequest.SerializeToString,
            scheduler__pb2.ShutdownAgentResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PollActivityBuffer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/agentos.scheduler.SchedulerService/PollActivityBuffer',
            scheduler__pb2.PollActivityBufferRequest.SerializeToString,
            scheduler__pb2.PollActivityBufferResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PurgeActivity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/agentos.scheduler.SchedulerService/PurgeActivity',
            scheduler__pb2.PurgeActivityRequest.SerializeToString,
            scheduler__pb2.PurgeActivityResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
