# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tool.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntool.proto\x12\x0c\x61gentos.tool\x1a\x1egoogle/protobuf/duration.proto\"\xde\x01\n\x0f\x45xecutionPolicy\x12*\n\x07timeout\x18\x01 \x01(\x0b\x32\x19.google.protobuf.Duration\x12\x13\n\x0bmax_retries\x18\x02 \x01(\r\x12\x0f\n\x07\x62\x61\x63koff\x18\x03 \x01(\t\x12\x19\n\x11worktree_required\x18\x04 \x01(\x08\x12\x16\n\x0enetwork_policy\x18\x05 \x01(\t\x12\x17\n\x0fprivilege_level\x18\x06 \x01(\t\x12\x15\n\rbudget_cpu_ms\x18\x07 \x01(\x04\x12\x16\n\x0e\x62udget_wall_ms\x18\x08 \x01(\x04\"\xa6\x01\n\x08ToolCall\x12\x0f\n\x07\x63\x61ll_id\x18\x01 \x01(\t\x12\x11\n\ttool_name\x18\x02 \x01(\t\x12\x13\n\x0bprovider_id\x18\x03 \x01(\t\x12\x14\n\x0c\x63ontent_type\x18\x04 \x01(\t\x12\x0c\n\x04\x61rgs\x18\x05 \x01(\x0c\x12-\n\x06policy\x18\x06 \x01(\x0b\x32\x1d.agentos.tool.ExecutionPolicy\x12\x0e\n\x06stream\x18\x07 \x01(\x08\"r\n\tToolFrame\x12\x0f\n\x07\x63\x61ll_id\x18\x01 \x01(\t\x12\x10\n\x08\x66rame_no\x18\x02 \x01(\x04\x12\r\n\x05\x66inal\x18\x03 \x01(\x08\x12\x14\n\x0c\x63ontent_type\x18\x04 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x05 \x01(\x0c\x12\x0f\n\x07summary\x18\x06 \x01(\x0c\"A\n\tToolError\x12\x0f\n\x07\x63\x61ll_id\x18\x01 \x01(\t\x12\x12\n\nerror_code\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t2\xc2\x01\n\x0bToolService\x12\x37\n\x04\x43\x61ll\x12\x16.agentos.tool.ToolCall\x1a\x17.agentos.tool.ToolFrame\x12?\n\nCallStream\x12\x16.agentos.tool.ToolCall\x1a\x17.agentos.tool.ToolFrame0\x01\x12\x39\n\x06\x43\x61ncel\x12\x16.agentos.tool.ToolCall\x1a\x17.agentos.tool.ToolErrorb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tool_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_EXECUTIONPOLICY']._serialized_start=61
  _globals['_EXECUTIONPOLICY']._serialized_end=283
  _globals['_TOOLCALL']._serialized_start=286
  _globals['_TOOLCALL']._serialized_end=452
  _globals['_TOOLFRAME']._serialized_start=454
  _globals['_TOOLFRAME']._serialized_end=568
  _globals['_TOOLERROR']._serialized_start=570
  _globals['_TOOLERROR']._serialized_end=635
  _globals['_TOOLSERVICE']._serialized_start=638
  _globals['_TOOLSERVICE']._serialized_end=832
# @@protoc_insertion_point(module_scope)
