# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import tool_pb2 as tool__pb2


class ToolServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Call = channel.unary_unary(
                '/agentos.tool.ToolService/Call',
                request_serializer=tool__pb2.ToolCall.SerializeToString,
                response_deserializer=tool__pb2.ToolFrame.FromString,
                )
        self.CallStream = channel.unary_stream(
                '/agentos.tool.ToolService/CallStream',
                request_serializer=tool__pb2.ToolCall.SerializeToString,
                response_deserializer=tool__pb2.ToolFrame.FromString,
                )
        self.Cancel = channel.unary_unary(
                '/agentos.tool.ToolService/Cancel',
                request_serializer=tool__pb2.ToolCall.SerializeToString,
                response_deserializer=tool__pb2.ToolError.FromString,
                )


class ToolServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Call(self, request, context):
        """unary completion
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CallStream(self, request, context):
        """streaming frames
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Cancel(self, request, context):
        """best effort
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ToolServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Call': grpc.unary_unary_rpc_method_handler(
                    servicer.Call,
                    request_deserializer=tool__pb2.ToolCall.FromString,
                    response_serializer=tool__pb2.ToolFrame.SerializeToString,
            ),
            'CallStream': grpc.unary_stream_rpc_method_handler(
                    servicer.CallStream,
                    request_deserializer=tool__pb2.ToolCall.FromString,
                    response_serializer=tool__pb2.ToolFrame.SerializeToString,
            ),
            'Cancel': grpc.unary_unary_rpc_method_handler(
                    servicer.Cancel,
                    request_deserializer=tool__pb2.ToolCall.FromString,
                    response_serializer=tool__pb2.ToolError.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agentos.tool.ToolService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ToolService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Call(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/agentos.tool.ToolService/Call',
            tool__pb2.ToolCall.SerializeToString,
            tool__pb2.ToolFrame.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CallStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/agentos.tool.ToolService/CallStream',
            tool__pb2.ToolCall.SerializeToString,
            tool__pb2.ToolFrame.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Cancel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/agentos.tool.ToolService/Cancel',
            tool__pb2.ToolCall.SerializeToString,
            tool__pb2.ToolError.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
