# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: worktree.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eworktree.proto\x12\x10\x61gentos.worktree\"E\n\x0b\x42indRequest\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\x12\x0f\n\x07repo_id\x18\x02 \x01(\t\x12\x13\n\x0bworktree_id\x18\x03 \x01(\t\"*\n\x0c\x42indResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0e\n\x06reason\x18\x02 \x01(\t\"!\n\rUnbindRequest\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\"\x1c\n\x0eUnbindResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\"T\n\rSwitchRequest\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\x12\x1a\n\x12target_worktree_id\x18\x02 \x01(\t\x12\x15\n\rrequires_hitl\x18\x03 \x01(\x08\"M\n\rSwitchApprove\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\x12\x1a\n\x12target_worktree_id\x18\x02 \x01(\t\x12\x0e\n\x06ttl_ms\x18\x03 \x01(\x04\"0\n\x0cSwitchReject\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\x12\x0e\n\x06reason\x18\x02 \x01(\t\"!\n\rStatusRequest\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\"E\n\x0eStatusResponse\x12\x0f\n\x07repo_id\x18\x01 \x01(\t\x12\x13\n\x0bworktree_id\x18\x02 \x01(\t\x12\r\n\x05state\x18\x03 \x01(\t2\xec\x03\n\x0fWorktreeService\x12\x45\n\x04\x42ind\x12\x1d.agentos.worktree.BindRequest\x1a\x1e.agentos.worktree.BindResponse\x12K\n\x06Unbind\x12\x1f.agentos.worktree.UnbindRequest\x1a .agentos.worktree.UnbindResponse\x12R\n\rRequestSwitch\x12\x1f.agentos.worktree.SwitchRequest\x1a .agentos.worktree.StatusResponse\x12R\n\rApproveSwitch\x12\x1f.agentos.worktree.SwitchApprove\x1a .agentos.worktree.StatusResponse\x12P\n\x0cRejectSwitch\x12\x1e.agentos.worktree.SwitchReject\x1a .agentos.worktree.StatusResponse\x12K\n\x06Status\x12\x1f.agentos.worktree.StatusRequest\x1a .agentos.worktree.StatusResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'worktree_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_BINDREQUEST']._serialized_start=36
  _globals['_BINDREQUEST']._serialized_end=105
  _globals['_BINDRESPONSE']._serialized_start=107
  _globals['_BINDRESPONSE']._serialized_end=149
  _globals['_UNBINDREQUEST']._serialized_start=151
  _globals['_UNBINDREQUEST']._serialized_end=184
  _globals['_UNBINDRESPONSE']._serialized_start=186
  _globals['_UNBINDRESPONSE']._serialized_end=214
  _globals['_SWITCHREQUEST']._serialized_start=216
  _globals['_SWITCHREQUEST']._serialized_end=300
  _globals['_SWITCHAPPROVE']._serialized_start=302
  _globals['_SWITCHAPPROVE']._serialized_end=379
  _globals['_SWITCHREJECT']._serialized_start=381
  _globals['_SWITCHREJECT']._serialized_end=429
  _globals['_STATUSREQUEST']._serialized_start=431
  _globals['_STATUSREQUEST']._serialized_end=464
  _globals['_STATUSRESPONSE']._serialized_start=466
  _globals['_STATUSRESPONSE']._serialized_end=535
  _globals['_WORKTREESERVICE']._serialized_start=538
  _globals['_WORKTREESERVICE']._serialized_end=1030
# @@protoc_insertion_point(module_scope)
