# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import worktree_pb2 as worktree__pb2


class WorktreeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Bind = channel.unary_unary(
                '/agentos.worktree.WorktreeService/Bind',
                request_serializer=worktree__pb2.BindRequest.SerializeToString,
                response_deserializer=worktree__pb2.BindResponse.FromString,
                )
        self.Unbind = channel.unary_unary(
                '/agentos.worktree.WorktreeService/Unbind',
                request_serializer=worktree__pb2.UnbindRequest.SerializeToString,
                response_deserializer=worktree__pb2.UnbindResponse.FromString,
                )
        self.RequestSwitch = channel.unary_unary(
                '/agentos.worktree.WorktreeService/RequestSwitch',
                request_serializer=worktree__pb2.SwitchRequest.SerializeToString,
                response_deserializer=worktree__pb2.StatusResponse.FromString,
                )
        self.ApproveSwitch = channel.unary_unary(
                '/agentos.worktree.WorktreeService/ApproveSwitch',
                request_serializer=worktree__pb2.SwitchApprove.SerializeToString,
                response_deserializer=worktree__pb2.StatusResponse.FromString,
                )
        self.RejectSwitch = channel.unary_unary(
                '/agentos.worktree.WorktreeService/RejectSwitch',
                request_serializer=worktree__pb2.SwitchReject.SerializeToString,
                response_deserializer=worktree__pb2.StatusResponse.FromString,
                )
        self.Status = channel.unary_unary(
                '/agentos.worktree.WorktreeService/Status',
                request_serializer=worktree__pb2.StatusRequest.SerializeToString,
                response_deserializer=worktree__pb2.StatusResponse.FromString,
                )


class WorktreeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Bind(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Unbind(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestSwitch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ApproveSwitch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RejectSwitch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Status(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorktreeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Bind': grpc.unary_unary_rpc_method_handler(
                    servicer.Bind,
                    request_deserializer=worktree__pb2.BindRequest.FromString,
                    response_serializer=worktree__pb2.BindResponse.SerializeToString,
            ),
            'Unbind': grpc.unary_unary_rpc_method_handler(
                    servicer.Unbind,
                    request_deserializer=worktree__pb2.UnbindRequest.FromString,
                    response_serializer=worktree__pb2.UnbindResponse.SerializeToString,
            ),
            'RequestSwitch': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestSwitch,
                    request_deserializer=worktree__pb2.SwitchRequest.FromString,
                    response_serializer=worktree__pb2.StatusResponse.SerializeToString,
            ),
            'ApproveSwitch': grpc.unary_unary_rpc_method_handler(
                    servicer.ApproveSwitch,
                    request_deserializer=worktree__pb2.SwitchApprove.FromString,
                    response_serializer=worktree__pb2.StatusResponse.SerializeToString,
            ),
            'RejectSwitch': grpc.unary_unary_rpc_method_handler(
                    servicer.RejectSwitch,
                    request_deserializer=worktree__pb2.SwitchReject.FromString,
                    response_serializer=worktree__pb2.StatusResponse.SerializeToString,
            ),
            'Status': grpc.unary_unary_rpc_method_handler(
                    servicer.Status,
                    request_deserializer=worktree__pb2.StatusRequest.FromString,
                    response_serializer=worktree__pb2.StatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agentos.worktree.WorktreeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class WorktreeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Bind(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/agentos.worktree.WorktreeService/Bind',
            worktree__pb2.BindRequest.SerializeToString,
            worktree__pb2.BindResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Unbind(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/agentos.worktree.WorktreeService/Unbind',
            worktree__pb2.UnbindRequest.SerializeToString,
            worktree__pb2.UnbindResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RequestSwitch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/agentos.worktree.WorktreeService/RequestSwitch',
            worktree__pb2.SwitchRequest.SerializeToString,
            worktree__pb2.StatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ApproveSwitch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/agentos.worktree.WorktreeService/ApproveSwitch',
            worktree__pb2.SwitchApprove.SerializeToString,
            worktree__pb2.StatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RejectSwitch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/agentos.worktree.WorktreeService/RejectSwitch',
            worktree__pb2.SwitchReject.SerializeToString,
            worktree__pb2.StatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Status(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/agentos.worktree.WorktreeService/Status',
            worktree__pb2.StatusRequest.SerializeToString,
            worktree__pb2.StatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
